//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipFlair.Windows.Base.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseWindowStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public BaseWindowStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipFlair.Windows.Base.Resources.BaseWindowStrings", typeof(BaseWindowStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
                
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close this window?.
        /// </summary>
        public static string msgCloseConfirmation {
            get {
                return ResourceManager.GetString("msgCloseConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string msgConfirmation {
            get {
                return ResourceManager.GetString("msgConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load .
        /// </summary>
        public static string msgLoad {
            get {
                return ResourceManager.GetString("msgLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipFlair archive (*.clipflair, *.clipflair.zip)|*.clipflair;*.clipflair.zip.
        /// </summary>
        public static string msgLoadFilter {
            get {
                return ResourceManager.GetString("msgLoadFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading failed.
        /// </summary>
        public static string msgLoadingFailed {
            get {
                return ResourceManager.GetString("msgLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading failed - Saved options may be for other window.
        /// </summary>
        public static string msgLoadingFailedOtherWindow {
            get {
                return ResourceManager.GetString("msgLoadingFailedOtherWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipFlair Component Template.
        /// </summary>
        public static string msgLoadURLDialogTitle {
            get {
                return ResourceManager.GetString("msgLoadURLDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClipFlair archive (*.clipflair)|*.clipflair|ClipFlair archive (*.clipflair.zip)|*.clipflair.zip.
        /// </summary>
        public static string msgSaveFilter {
            get {
                return ResourceManager.GetString("msgSaveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving failed.
        /// </summary>
        public static string msgSavingFailed {
            get {
                return ResourceManager.GetString("msgSavingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown view type: .
        /// </summary>
        public static string msgUnknownViewType {
            get {
                return ResourceManager.GetString("msgUnknownViewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        public static string msgURL {
            get {
                return ResourceManager.GetString("msgURL", resourceCulture);
            }
        }
    }
}
