//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipFlair.CaptionsGrid.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipFlair.CaptionsGrid.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add caption at current time.
        /// </summary>
        public static string tooltip_caption_add {
            get {
                return ResourceManager.GetString("tooltip_caption_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set selected caption&apos;s end time.
        /// </summary>
        public static string tooltip_caption_end {
            get {
                return ResourceManager.GetString("tooltip_caption_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected caption.
        /// </summary>
        public static string tooltip_caption_remove {
            get {
                return ResourceManager.GetString("tooltip_caption_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set selected caption&apos;s start time.
        /// </summary>
        public static string tooltip_caption_start {
            get {
                return ResourceManager.GetString("tooltip_caption_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export captions to TTS, SRT and other file formats.
        /// </summary>
        public static string tooltip_captions_export {
            get {
                return ResourceManager.GetString("tooltip_captions_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import captions from TTS, SRT and other file formats.
        /// </summary>
        public static string tooltip_captions_import {
            get {
                return ResourceManager.GetString("tooltip_captions_import", resourceCulture);
            }
        }
    }
}
