//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoSoftware.MonoX.Resources {
    using System;
    using System.Web.Configuration;
    using MonoSoftware.Web.ResourceProviderModel;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorProviderModel custom tool. (Mono Wrapper based on Dmytro Kryvko builder)
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorProviderModel custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2014 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MonoSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "4.8.40.4594")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class BlogResources {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BlogResources() {
        }
        
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            System.Threading.Interlocked.Exchange(ref _resourceManager, MonoSoftware.Web.ResourceProviderModel.ResourceManagerProvider.GetResourceManager("MonoSoftware.MonoX.MonoX.Resources.BlogResources", typeof(BlogResources).Assembly));
                        }
                    }
                    finally {
                        System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'AddNewPost'.
        /// </summary>
        public static string AddNewPost_PropertyName {
            get {
                return "AddNewPost";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Add new blog post'.
        /// </summary>
        public static string AddNewPost {
            get {
                return ResourceManager.GetString("AddNewPost", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'AllBlogPosts'.
        /// </summary>
        public static string AllBlogPosts_PropertyName {
            get {
                return "AllBlogPosts";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'All blog posts'.
        /// </summary>
        public static string AllBlogPosts {
            get {
                return ResourceManager.GetString("AllBlogPosts", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'AllCategories'.
        /// </summary>
        public static string AllCategories_PropertyName {
            get {
                return "AllCategories";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'All'.
        /// </summary>
        public static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Author'.
        /// </summary>
        public static string Author_PropertyName {
            get {
                return "Author";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Author'.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'AuthorDescriptionFormatString'.
        /// </summary>
        public static string AuthorDescriptionFormatString_PropertyName {
            get {
                return "AuthorDescriptionFormatString";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Posts authored by {0}'.
        /// </summary>
        public static string AuthorDescriptionFormatString {
            get {
                return ResourceManager.GetString("AuthorDescriptionFormatString", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'BlogCategories_NoData'.
        /// </summary>
        public static string BlogCategories_NoData_PropertyName {
            get {
                return "BlogCategories_NoData";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'There are no published categories for this blog.'.
        /// </summary>
        public static string BlogCategories_NoData {
            get {
                return ResourceManager.GetString("BlogCategories_NoData", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'BlogEditors'.
        /// </summary>
        public static string BlogEditors_PropertyName {
            get {
                return "BlogEditors";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Blog editors'.
        /// </summary>
        public static string BlogEditors {
            get {
                return ResourceManager.GetString("BlogEditors", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'BlogInfo'.
        /// </summary>
        public static string BlogInfo_PropertyName {
            get {
                return "BlogInfo";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Blog info'.
        /// </summary>
        public static string BlogInfo {
            get {
                return ResourceManager.GetString("BlogInfo", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'BlogList'.
        /// </summary>
        public static string BlogList_PropertyName {
            get {
                return "BlogList";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Blog list'.
        /// </summary>
        public static string BlogList {
            get {
                return ResourceManager.GetString("BlogList", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'BlogManageCategories_AddNew'.
        /// </summary>
        public static string BlogManageCategories_AddNew_PropertyName {
            get {
                return "BlogManageCategories_AddNew";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Add category'.
        /// </summary>
        public static string BlogManageCategories_AddNew {
            get {
                return ResourceManager.GetString("BlogManageCategories_AddNew", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'BlogManageCategories_Categories'.
        /// </summary>
        public static string BlogManageCategories_Categories_PropertyName {
            get {
                return "BlogManageCategories_Categories";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Blog categories'.
        /// </summary>
        public static string BlogManageCategories_Categories {
            get {
                return ResourceManager.GetString("BlogManageCategories_Categories", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'BlogManageCategories_Update'.
        /// </summary>
        public static string BlogManageCategories_Update_PropertyName {
            get {
                return "BlogManageCategories_Update";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Update'.
        /// </summary>
        public static string BlogManageCategories_Update {
            get {
                return ResourceManager.GetString("BlogManageCategories_Update", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'BlogPost_NewCommentAdded'.
        /// </summary>
        public static string BlogPost_NewCommentAdded_PropertyName {
            get {
                return "BlogPost_NewCommentAdded";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'A new comment has been added to a blog post that you are subscribed on.'.
        /// </summary>
        public static string BlogPost_NewCommentAdded {
            get {
                return ResourceManager.GetString("BlogPost_NewCommentAdded", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'BlogPost_NewCommentClickToReply'.
        /// </summary>
        public static string BlogPost_NewCommentClickToReply_PropertyName {
            get {
                return "BlogPost_NewCommentClickToReply";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Click here to post a reply.'.
        /// </summary>
        public static string BlogPost_NewCommentClickToReply {
            get {
                return ResourceManager.GetString("BlogPost_NewCommentClickToReply", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'BlogPostList_Filter_ShowAll'.
        /// </summary>
        public static string BlogPostList_Filter_ShowAll_PropertyName {
            get {
                return "BlogPostList_Filter_ShowAll";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'All posts'.
        /// </summary>
        public static string BlogPostList_Filter_ShowAll {
            get {
                return ResourceManager.GetString("BlogPostList_Filter_ShowAll", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'BlogPostList_Filter_ShowAllToolTip'.
        /// </summary>
        public static string BlogPostList_Filter_ShowAllToolTip_PropertyName {
            get {
                return "BlogPostList_Filter_ShowAllToolTip";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Show all posts'.
        /// </summary>
        public static string BlogPostList_Filter_ShowAllToolTip {
            get {
                return ResourceManager.GetString("BlogPostList_Filter_ShowAllToolTip", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'BlogPostList_Filter_ShowPublished'.
        /// </summary>
        public static string BlogPostList_Filter_ShowPublished_PropertyName {
            get {
                return "BlogPostList_Filter_ShowPublished";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Published posts'.
        /// </summary>
        public static string BlogPostList_Filter_ShowPublished {
            get {
                return ResourceManager.GetString("BlogPostList_Filter_ShowPublished", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'BlogPostList_Filter_ShowPublishedToolTip'.
        /// </summary>
        public static string BlogPostList_Filter_ShowPublishedToolTip_PropertyName {
            get {
                return "BlogPostList_Filter_ShowPublishedToolTip";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Show only published posts'.
        /// </summary>
        public static string BlogPostList_Filter_ShowPublishedToolTip {
            get {
                return ResourceManager.GetString("BlogPostList_Filter_ShowPublishedToolTip", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'BlogPostList_Filter_ShowUnPublished'.
        /// </summary>
        public static string BlogPostList_Filter_ShowUnPublished_PropertyName {
            get {
                return "BlogPostList_Filter_ShowUnPublished";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Unpublished posts'.
        /// </summary>
        public static string BlogPostList_Filter_ShowUnPublished {
            get {
                return ResourceManager.GetString("BlogPostList_Filter_ShowUnPublished", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'BlogPostList_Filter_ShowUnPublishedToolTip'.
        /// </summary>
        public static string BlogPostList_Filter_ShowUnPublishedToolTip_PropertyName {
            get {
                return "BlogPostList_Filter_ShowUnPublishedToolTip";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Show only unpublished posts'.
        /// </summary>
        public static string BlogPostList_Filter_ShowUnPublishedToolTip {
            get {
                return ResourceManager.GetString("BlogPostList_Filter_ShowUnPublishedToolTip", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'BlogPostList_Filter_Title'.
        /// </summary>
        public static string BlogPostList_Filter_Title_PropertyName {
            get {
                return "BlogPostList_Filter_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Current filter'.
        /// </summary>
        public static string BlogPostList_Filter_Title {
            get {
                return ResourceManager.GetString("BlogPostList_Filter_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'BlogSettings'.
        /// </summary>
        public static string BlogSettings_PropertyName {
            get {
                return "BlogSettings";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Blog settings'.
        /// </summary>
        public static string BlogSettings {
            get {
                return ResourceManager.GetString("BlogSettings", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'BlogSettings_Description'.
        /// </summary>
        public static string BlogSettings_Description_PropertyName {
            get {
                return "BlogSettings_Description";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Description:'.
        /// </summary>
        public static string BlogSettings_Description {
            get {
                return ResourceManager.GetString("BlogSettings_Description", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Categories'.
        /// </summary>
        public static string Categories_PropertyName {
            get {
                return "Categories";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Categories'.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'CategoryDescriptionFormatString'.
        /// </summary>
        public static string CategoryDescriptionFormatString_PropertyName {
            get {
                return "CategoryDescriptionFormatString";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Posts in category {0}'.
        /// </summary>
        public static string CategoryDescriptionFormatString {
            get {
                return ResourceManager.GetString("CategoryDescriptionFormatString", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments'.
        /// </summary>
        public static string Comments_PropertyName {
            get {
                return "Comments";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Comments'.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_ApprovalAlert'.
        /// </summary>
        public static string Comments_ApprovalAlert_PropertyName {
            get {
                return "Comments_ApprovalAlert";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Your comment may require administrative approval before it is published. '.
        /// </summary>
        public static string Comments_ApprovalAlert {
            get {
                return ResourceManager.GetString("Comments_ApprovalAlert", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_Approve'.
        /// </summary>
        public static string Comments_Approve_PropertyName {
            get {
                return "Comments_Approve";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Approve'.
        /// </summary>
        public static string Comments_Approve {
            get {
                return ResourceManager.GetString("Comments_Approve", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_Comment'.
        /// </summary>
        public static string Comments_Comment_PropertyName {
            get {
                return "Comments_Comment";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Comment'.
        /// </summary>
        public static string Comments_Comment {
            get {
                return ResourceManager.GetString("Comments_Comment", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_Comments'.
        /// </summary>
        public static string Comments_Comments_PropertyName {
            get {
                return "Comments_Comments";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Comments'.
        /// </summary>
        public static string Comments_Comments {
            get {
                return ResourceManager.GetString("Comments_Comments", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_ConfirmDelete'.
        /// </summary>
        public static string Comments_ConfirmDelete_PropertyName {
            get {
                return "Comments_ConfirmDelete";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'This blog comment will be deleted. Are you sure?'.
        /// </summary>
        public static string Comments_ConfirmDelete {
            get {
                return ResourceManager.GetString("Comments_ConfirmDelete", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_Email'.
        /// </summary>
        public static string Comments_Email_PropertyName {
            get {
                return "Comments_Email";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'E-mail:*'.
        /// </summary>
        public static string Comments_Email {
            get {
                return ResourceManager.GetString("Comments_Email", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_ErrorMessage_Comments'.
        /// </summary>
        public static string Comments_ErrorMessage_Comments_PropertyName {
            get {
                return "Comments_ErrorMessage_Comments";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Please enter a valid comment.'.
        /// </summary>
        public static string Comments_ErrorMessage_Comments {
            get {
                return ResourceManager.GetString("Comments_ErrorMessage_Comments", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_ErrorMessage_EmailFormat'.
        /// </summary>
        public static string Comments_ErrorMessage_EmailFormat_PropertyName {
            get {
                return "Comments_ErrorMessage_EmailFormat";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Please enter a correct e-mail address'.
        /// </summary>
        public static string Comments_ErrorMessage_EmailFormat {
            get {
                return ResourceManager.GetString("Comments_ErrorMessage_EmailFormat", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_ErrorMessage_EmailRequired'.
        /// </summary>
        public static string Comments_ErrorMessage_EmailRequired_PropertyName {
            get {
                return "Comments_ErrorMessage_EmailRequired";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Please enter your e-mail address. It will not be shown publicly.'.
        /// </summary>
        public static string Comments_ErrorMessage_EmailRequired {
            get {
                return ResourceManager.GetString("Comments_ErrorMessage_EmailRequired", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_ErrorMessage_Name'.
        /// </summary>
        public static string Comments_ErrorMessage_Name_PropertyName {
            get {
                return "Comments_ErrorMessage_Name";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Please enter your name.'.
        /// </summary>
        public static string Comments_ErrorMessage_Name {
            get {
                return ResourceManager.GetString("Comments_ErrorMessage_Name", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_ErrorMessage_UrlFormat'.
        /// </summary>
        public static string Comments_ErrorMessage_UrlFormat_PropertyName {
            get {
                return "Comments_ErrorMessage_UrlFormat";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Please enter a correct Web site address, starting with http:// prefix.'.
        /// </summary>
        public static string Comments_ErrorMessage_UrlFormat {
            get {
                return ResourceManager.GetString("Comments_ErrorMessage_UrlFormat", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_MailSubject'.
        /// </summary>
        public static string Comments_MailSubject_PropertyName {
            get {
                return "Comments_MailSubject";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '{0} has commented on {1}'.
        /// </summary>
        public static string Comments_MailSubject {
            get {
                return ResourceManager.GetString("Comments_MailSubject", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_Name'.
        /// </summary>
        public static string Comments_Name_PropertyName {
            get {
                return "Comments_Name";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Name:*'.
        /// </summary>
        public static string Comments_Name {
            get {
                return ResourceManager.GetString("Comments_Name", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_Notify'.
        /// </summary>
        public static string Comments_Notify_PropertyName {
            get {
                return "Comments_Notify";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Notify me when new comments are added to this post'.
        /// </summary>
        public static string Comments_Notify {
            get {
                return ResourceManager.GetString("Comments_Notify", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_ReportHam'.
        /// </summary>
        public static string Comments_ReportHam_PropertyName {
            get {
                return "Comments_ReportHam";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Report as ham'.
        /// </summary>
        public static string Comments_ReportHam {
            get {
                return ResourceManager.GetString("Comments_ReportHam", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_ReportSpam'.
        /// </summary>
        public static string Comments_ReportSpam_PropertyName {
            get {
                return "Comments_ReportSpam";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Report as spam'.
        /// </summary>
        public static string Comments_ReportSpam {
            get {
                return ResourceManager.GetString("Comments_ReportSpam", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_Save'.
        /// </summary>
        public static string Comments_Save_PropertyName {
            get {
                return "Comments_Save";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Save comment'.
        /// </summary>
        public static string Comments_Save {
            get {
                return ResourceManager.GetString("Comments_Save", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_Sender_Url'.
        /// </summary>
        public static string Comments_Sender_Url_PropertyName {
            get {
                return "Comments_Sender_Url";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Sender&apos;s URL:'.
        /// </summary>
        public static string Comments_Sender_Url {
            get {
                return ResourceManager.GetString("Comments_Sender_Url", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_Url'.
        /// </summary>
        public static string Comments_Url_PropertyName {
            get {
                return "Comments_Url";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Web site:'.
        /// </summary>
        public static string Comments_Url {
            get {
                return ResourceManager.GetString("Comments_Url", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Comments_ValidationSummary'.
        /// </summary>
        public static string Comments_ValidationSummary_PropertyName {
            get {
                return "Comments_ValidationSummary";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The following issues have to be resolved before you can proceed:'.
        /// </summary>
        public static string Comments_ValidationSummary {
            get {
                return ResourceManager.GetString("Comments_ValidationSummary", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'CommentsAdmin'.
        /// </summary>
        public static string CommentsAdmin_PropertyName {
            get {
                return "CommentsAdmin";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Comments'.
        /// </summary>
        public static string CommentsAdmin {
            get {
                return ResourceManager.GetString("CommentsAdmin", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'ConfirmDelete'.
        /// </summary>
        public static string ConfirmDelete_PropertyName {
            get {
                return "ConfirmDelete";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'This blog post will be deleted. Are you sure?'.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'ConfirmDeleteSpam'.
        /// </summary>
        public static string ConfirmDeleteSpam_PropertyName {
            get {
                return "ConfirmDeleteSpam";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'All comments marked as spam will be deleted. Are you sure?'.
        /// </summary>
        public static string ConfirmDeleteSpam {
            get {
                return ResourceManager.GetString("ConfirmDeleteSpam", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'ConfirmDeleteUnapproved'.
        /// </summary>
        public static string ConfirmDeleteUnapproved_PropertyName {
            get {
                return "ConfirmDeleteUnapproved";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'All unapproved comments will be deleted. Are you sure?'.
        /// </summary>
        public static string ConfirmDeleteUnapproved {
            get {
                return ResourceManager.GetString("ConfirmDeleteUnapproved", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Delete'.
        /// </summary>
        public static string Delete_PropertyName {
            get {
                return "Delete";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Delete'.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'DeleteSpam'.
        /// </summary>
        public static string DeleteSpam_PropertyName {
            get {
                return "DeleteSpam";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Delete spam'.
        /// </summary>
        public static string DeleteSpam {
            get {
                return ResourceManager.GetString("DeleteSpam", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'DeleteUnapproved'.
        /// </summary>
        public static string DeleteUnapproved_PropertyName {
            get {
                return "DeleteUnapproved";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Delete unapproved'.
        /// </summary>
        public static string DeleteUnapproved {
            get {
                return ResourceManager.GetString("DeleteUnapproved", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit'.
        /// </summary>
        public static string Edit_PropertyName {
            get {
                return "Edit";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Edit'.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_Application'.
        /// </summary>
        public static string Edit_Application_PropertyName {
            get {
                return "Edit_Application";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Application:'.
        /// </summary>
        public static string Edit_Application {
            get {
                return ResourceManager.GetString("Edit_Application", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_Attachments'.
        /// </summary>
        public static string Edit_Attachments_PropertyName {
            get {
                return "Edit_Attachments";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Attachments:'.
        /// </summary>
        public static string Edit_Attachments {
            get {
                return ResourceManager.GetString("Edit_Attachments", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_BlogTitle'.
        /// </summary>
        public static string Edit_BlogTitle_PropertyName {
            get {
                return "Edit_BlogTitle";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Blog title:'.
        /// </summary>
        public static string Edit_BlogTitle {
            get {
                return ResourceManager.GetString("Edit_BlogTitle", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_Cancel'.
        /// </summary>
        public static string Edit_Cancel_PropertyName {
            get {
                return "Edit_Cancel";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '(C)ancel'.
        /// </summary>
        public static string Edit_Cancel {
            get {
                return ResourceManager.GetString("Edit_Cancel", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_Cancel_AccessKey'.
        /// </summary>
        public static string Edit_Cancel_AccessKey_PropertyName {
            get {
                return "Edit_Cancel_AccessKey";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'C'.
        /// </summary>
        public static string Edit_Cancel_AccessKey {
            get {
                return ResourceManager.GetString("Edit_Cancel_AccessKey", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_Categories'.
        /// </summary>
        public static string Edit_Categories_PropertyName {
            get {
                return "Edit_Categories";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Categories:'.
        /// </summary>
        public static string Edit_Categories {
            get {
                return ResourceManager.GetString("Edit_Categories", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_Content'.
        /// </summary>
        public static string Edit_Content_PropertyName {
            get {
                return "Edit_Content";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Blog post content:'.
        /// </summary>
        public static string Edit_Content {
            get {
                return ResourceManager.GetString("Edit_Content", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_Description'.
        /// </summary>
        public static string Edit_Description_PropertyName {
            get {
                return "Edit_Description";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Excerpt:'.
        /// </summary>
        public static string Edit_Description {
            get {
                return ResourceManager.GetString("Edit_Description", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_EditCategories'.
        /// </summary>
        public static string Edit_EditCategories_PropertyName {
            get {
                return "Edit_EditCategories";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Edit blog categories'.
        /// </summary>
        public static string Edit_EditCategories {
            get {
                return ResourceManager.GetString("Edit_EditCategories", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_ErrorMessage_AlreadyExits'.
        /// </summary>
        public static string Edit_ErrorMessage_AlreadyExits_PropertyName {
            get {
                return "Edit_ErrorMessage_AlreadyExits";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Blog with similar title already exists.'.
        /// </summary>
        public static string Edit_ErrorMessage_AlreadyExits {
            get {
                return ResourceManager.GetString("Edit_ErrorMessage_AlreadyExits", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_ErrorMessage_TitleRequired'.
        /// </summary>
        public static string Edit_ErrorMessage_TitleRequired_PropertyName {
            get {
                return "Edit_ErrorMessage_TitleRequired";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Please fill in the title field!'.
        /// </summary>
        public static string Edit_ErrorMessage_TitleRequired {
            get {
                return ResourceManager.GetString("Edit_ErrorMessage_TitleRequired", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_IsCommentingAllowed'.
        /// </summary>
        public static string Edit_IsCommentingAllowed_PropertyName {
            get {
                return "Edit_IsCommentingAllowed";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Allow comments ?'.
        /// </summary>
        public static string Edit_IsCommentingAllowed {
            get {
                return ResourceManager.GetString("Edit_IsCommentingAllowed", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_IsPublished'.
        /// </summary>
        public static string Edit_IsPublished_PropertyName {
            get {
                return "Edit_IsPublished";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Publish post ?'.
        /// </summary>
        public static string Edit_IsPublished {
            get {
                return ResourceManager.GetString("Edit_IsPublished", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_PublishDate'.
        /// </summary>
        public static string Edit_PublishDate_PropertyName {
            get {
                return "Edit_PublishDate";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Publish on:'.
        /// </summary>
        public static string Edit_PublishDate {
            get {
                return ResourceManager.GetString("Edit_PublishDate", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_Roles'.
        /// </summary>
        public static string Edit_Roles_PropertyName {
            get {
                return "Edit_Roles";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'View roles (by default, all users can view the blog post):'.
        /// </summary>
        public static string Edit_Roles {
            get {
                return ResourceManager.GetString("Edit_Roles", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_Save'.
        /// </summary>
        public static string Edit_Save_PropertyName {
            get {
                return "Edit_Save";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '(P)ublish'.
        /// </summary>
        public static string Edit_Save {
            get {
                return ResourceManager.GetString("Edit_Save", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_Save_AccessKey'.
        /// </summary>
        public static string Edit_Save_AccessKey_PropertyName {
            get {
                return "Edit_Save_AccessKey";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'P'.
        /// </summary>
        public static string Edit_Save_AccessKey {
            get {
                return ResourceManager.GetString("Edit_Save_AccessKey", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_Tags'.
        /// </summary>
        public static string Edit_Tags_PropertyName {
            get {
                return "Edit_Tags";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Tags:'.
        /// </summary>
        public static string Edit_Tags {
            get {
                return ResourceManager.GetString("Edit_Tags", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_TagTheNet'.
        /// </summary>
        public static string Edit_TagTheNet_PropertyName {
            get {
                return "Edit_TagTheNet";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'TagThe.Net'.
        /// </summary>
        public static string Edit_TagTheNet {
            get {
                return ResourceManager.GetString("Edit_TagTheNet", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_Title'.
        /// </summary>
        public static string Edit_Title_PropertyName {
            get {
                return "Edit_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Blog post title:'.
        /// </summary>
        public static string Edit_Title {
            get {
                return ResourceManager.GetString("Edit_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_ValidationSummary'.
        /// </summary>
        public static string Edit_ValidationSummary_PropertyName {
            get {
                return "Edit_ValidationSummary";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The following issues have to be resolved before you can proceed:'.
        /// </summary>
        public static string Edit_ValidationSummary {
            get {
                return ResourceManager.GetString("Edit_ValidationSummary", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit_Yahoo'.
        /// </summary>
        public static string Edit_Yahoo_PropertyName {
            get {
                return "Edit_Yahoo";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Yahoo Term Extraction'.
        /// </summary>
        public static string Edit_Yahoo {
            get {
                return ResourceManager.GetString("Edit_Yahoo", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Email'.
        /// </summary>
        public static string Email_PropertyName {
            get {
                return "Email";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'E-mail'.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Home'.
        /// </summary>
        public static string Home_PropertyName {
            get {
                return "Home";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Blog home'.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'InvitationText'.
        /// </summary>
        public static string InvitationText_PropertyName {
            get {
                return "InvitationText";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'I thought you might like this blog post'.
        /// </summary>
        public static string InvitationText {
            get {
                return ResourceManager.GetString("InvitationText", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'NoBlogPostsWarning'.
        /// </summary>
        public static string NoBlogPostsWarning_PropertyName {
            get {
                return "NoBlogPostsWarning";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '&lt;br /&gt;No blog posts were found for the required criteria.&lt;br /&gt;'.
        /// </summary>
        public static string NoBlogPostsWarning {
            get {
                return ResourceManager.GetString("NoBlogPostsWarning", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'NoRatingText'.
        /// </summary>
        public static string NoRatingText_PropertyName {
            get {
                return "NoRatingText";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'This post has not been rated yet.'.
        /// </summary>
        public static string NoRatingText {
            get {
                return ResourceManager.GetString("NoRatingText", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'OtherArticlesByAuthor'.
        /// </summary>
        public static string OtherArticlesByAuthor_PropertyName {
            get {
                return "OtherArticlesByAuthor";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Other articles by:'.
        /// </summary>
        public static string OtherArticlesByAuthor {
            get {
                return ResourceManager.GetString("OtherArticlesByAuthor", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PostCannotBeFound'.
        /// </summary>
        public static string PostCannotBeFound_PropertyName {
            get {
                return "PostCannotBeFound";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The requested post cannot be found. You may entered the incorrect address, or the post was deleted by the author.'.
        /// </summary>
        public static string PostCannotBeFound {
            get {
                return ResourceManager.GetString("PostCannotBeFound", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Publish'.
        /// </summary>
        public static string Publish_PropertyName {
            get {
                return "Publish";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Publish'.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'RatingText'.
        /// </summary>
        public static string RatingText_PropertyName {
            get {
                return "RatingText";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Currently rated {0:f2} by {1} visitor(s)'.
        /// </summary>
        public static string RatingText {
            get {
                return ResourceManager.GetString("RatingText", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'RelatedContent'.
        /// </summary>
        public static string RelatedContent_PropertyName {
            get {
                return "RelatedContent";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Related blog posts'.
        /// </summary>
        public static string RelatedContent {
            get {
                return ResourceManager.GetString("RelatedContent", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'SearchDescriptionFormatString'.
        /// </summary>
        public static string SearchDescriptionFormatString_PropertyName {
            get {
                return "SearchDescriptionFormatString";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Posts with keyword(s): {0}'.
        /// </summary>
        public static string SearchDescriptionFormatString {
            get {
                return ResourceManager.GetString("SearchDescriptionFormatString", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Settings_EditorsTooltip'.
        /// </summary>
        public static string Settings_EditorsTooltip_PropertyName {
            get {
                return "Settings_EditorsTooltip";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Tip: Enter comma-separated list of user names you want to set as editors of this blog.'.
        /// </summary>
        public static string Settings_EditorsTooltip {
            get {
                return ResourceManager.GetString("Settings_EditorsTooltip", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Spam'.
        /// </summary>
        public static string Spam_PropertyName {
            get {
                return "Spam";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Spam'.
        /// </summary>
        public static string Spam {
            get {
                return ResourceManager.GetString("Spam", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'TagDescriptionFormatString'.
        /// </summary>
        public static string TagDescriptionFormatString_PropertyName {
            get {
                return "TagDescriptionFormatString";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Posts tagged with {0}'.
        /// </summary>
        public static string TagDescriptionFormatString {
            get {
                return ResourceManager.GetString("TagDescriptionFormatString", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Tags'.
        /// </summary>
        public static string Tags_PropertyName {
            get {
                return "Tags";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Tags'.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Unapproved'.
        /// </summary>
        public static string Unapproved_PropertyName {
            get {
                return "Unapproved";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Unapproved'.
        /// </summary>
        public static string Unapproved {
            get {
                return ResourceManager.GetString("Unapproved", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Unpublish'.
        /// </summary>
        public static string Unpublish_PropertyName {
            get {
                return "Unpublish";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Unpublish'.
        /// </summary>
        public static string Unpublish {
            get {
                return ResourceManager.GetString("Unpublish", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Unpublished'.
        /// </summary>
        public static string Unpublished_PropertyName {
            get {
                return "Unpublished";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Unpublished'.
        /// </summary>
        public static string Unpublished {
            get {
                return ResourceManager.GetString("Unpublished", _resourceCulture);
            }
        }
        
        /// <summary>
        /// The stub formatting method returning the AddNewPost property value.
        /// </summary>
        /// <returns>The AddNewPost property value.</returns>
        public static string AddNewPostFormat() {
            return AddNewPost;
        }
        
        /// <summary>
        /// The stub formatting method returning the AllBlogPosts property value.
        /// </summary>
        /// <returns>The AllBlogPosts property value.</returns>
        public static string AllBlogPostsFormat() {
            return AllBlogPosts;
        }
        
        /// <summary>
        /// The stub formatting method returning the AllCategories property value.
        /// </summary>
        /// <returns>The AllCategories property value.</returns>
        public static string AllCategoriesFormat() {
            return AllCategories;
        }
        
        /// <summary>
        /// The stub formatting method returning the Author property value.
        /// </summary>
        /// <returns>The Author property value.</returns>
        public static string AuthorFormat() {
            return Author;
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Posts authored by {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string AuthorDescriptionFormatStringFormat(object arg0) {
            return string.Format(_resourceCulture, AuthorDescriptionFormatString, arg0);
        }
        
        /// <summary>
        /// The stub formatting method returning the BlogCategories_NoData property value.
        /// </summary>
        /// <returns>The BlogCategories_NoData property value.</returns>
        public static string BlogCategories_NoDataFormat() {
            return BlogCategories_NoData;
        }
        
        /// <summary>
        /// The stub formatting method returning the BlogEditors property value.
        /// </summary>
        /// <returns>The BlogEditors property value.</returns>
        public static string BlogEditorsFormat() {
            return BlogEditors;
        }
        
        /// <summary>
        /// The stub formatting method returning the BlogInfo property value.
        /// </summary>
        /// <returns>The BlogInfo property value.</returns>
        public static string BlogInfoFormat() {
            return BlogInfo;
        }
        
        /// <summary>
        /// The stub formatting method returning the BlogList property value.
        /// </summary>
        /// <returns>The BlogList property value.</returns>
        public static string BlogListFormat() {
            return BlogList;
        }
        
        /// <summary>
        /// The stub formatting method returning the BlogManageCategories_AddNew property value.
        /// </summary>
        /// <returns>The BlogManageCategories_AddNew property value.</returns>
        public static string BlogManageCategories_AddNewFormat() {
            return BlogManageCategories_AddNew;
        }
        
        /// <summary>
        /// The stub formatting method returning the BlogManageCategories_Categories property value.
        /// </summary>
        /// <returns>The BlogManageCategories_Categories property value.</returns>
        public static string BlogManageCategories_CategoriesFormat() {
            return BlogManageCategories_Categories;
        }
        
        /// <summary>
        /// The stub formatting method returning the BlogManageCategories_Update property value.
        /// </summary>
        /// <returns>The BlogManageCategories_Update property value.</returns>
        public static string BlogManageCategories_UpdateFormat() {
            return BlogManageCategories_Update;
        }
        
        /// <summary>
        /// The stub formatting method returning the BlogPost_NewCommentAdded property value.
        /// </summary>
        /// <returns>The BlogPost_NewCommentAdded property value.</returns>
        public static string BlogPost_NewCommentAddedFormat() {
            return BlogPost_NewCommentAdded;
        }
        
        /// <summary>
        /// The stub formatting method returning the BlogPost_NewCommentClickToReply property value.
        /// </summary>
        /// <returns>The BlogPost_NewCommentClickToReply property value.</returns>
        public static string BlogPost_NewCommentClickToReplyFormat() {
            return BlogPost_NewCommentClickToReply;
        }
        
        /// <summary>
        /// The stub formatting method returning the BlogPostList_Filter_ShowAll property value.
        /// </summary>
        /// <returns>The BlogPostList_Filter_ShowAll property value.</returns>
        public static string BlogPostList_Filter_ShowAllFormat() {
            return BlogPostList_Filter_ShowAll;
        }
        
        /// <summary>
        /// The stub formatting method returning the BlogPostList_Filter_ShowAllToolTip property value.
        /// </summary>
        /// <returns>The BlogPostList_Filter_ShowAllToolTip property value.</returns>
        public static string BlogPostList_Filter_ShowAllToolTipFormat() {
            return BlogPostList_Filter_ShowAllToolTip;
        }
        
        /// <summary>
        /// The stub formatting method returning the BlogPostList_Filter_ShowPublished property value.
        /// </summary>
        /// <returns>The BlogPostList_Filter_ShowPublished property value.</returns>
        public static string BlogPostList_Filter_ShowPublishedFormat() {
            return BlogPostList_Filter_ShowPublished;
        }
        
        /// <summary>
        /// The stub formatting method returning the BlogPostList_Filter_ShowPublishedToolTip property value.
        /// </summary>
        /// <returns>The BlogPostList_Filter_ShowPublishedToolTip property value.</returns>
        public static string BlogPostList_Filter_ShowPublishedToolTipFormat() {
            return BlogPostList_Filter_ShowPublishedToolTip;
        }
        
        /// <summary>
        /// The stub formatting method returning the BlogPostList_Filter_ShowUnPublished property value.
        /// </summary>
        /// <returns>The BlogPostList_Filter_ShowUnPublished property value.</returns>
        public static string BlogPostList_Filter_ShowUnPublishedFormat() {
            return BlogPostList_Filter_ShowUnPublished;
        }
        
        /// <summary>
        /// The stub formatting method returning the BlogPostList_Filter_ShowUnPublishedToolTip property value.
        /// </summary>
        /// <returns>The BlogPostList_Filter_ShowUnPublishedToolTip property value.</returns>
        public static string BlogPostList_Filter_ShowUnPublishedToolTipFormat() {
            return BlogPostList_Filter_ShowUnPublishedToolTip;
        }
        
        /// <summary>
        /// The stub formatting method returning the BlogPostList_Filter_Title property value.
        /// </summary>
        /// <returns>The BlogPostList_Filter_Title property value.</returns>
        public static string BlogPostList_Filter_TitleFormat() {
            return BlogPostList_Filter_Title;
        }
        
        /// <summary>
        /// The stub formatting method returning the BlogSettings property value.
        /// </summary>
        /// <returns>The BlogSettings property value.</returns>
        public static string BlogSettingsFormat() {
            return BlogSettings;
        }
        
        /// <summary>
        /// The stub formatting method returning the BlogSettings_Description property value.
        /// </summary>
        /// <returns>The BlogSettings_Description property value.</returns>
        public static string BlogSettings_DescriptionFormat() {
            return BlogSettings_Description;
        }
        
        /// <summary>
        /// The stub formatting method returning the Categories property value.
        /// </summary>
        /// <returns>The Categories property value.</returns>
        public static string CategoriesFormat() {
            return Categories;
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Posts in category {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string CategoryDescriptionFormatStringFormat(object arg0) {
            return string.Format(_resourceCulture, CategoryDescriptionFormatString, arg0);
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments property value.
        /// </summary>
        /// <returns>The Comments property value.</returns>
        public static string CommentsFormat() {
            return Comments;
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_ApprovalAlert property value.
        /// </summary>
        /// <returns>The Comments_ApprovalAlert property value.</returns>
        public static string Comments_ApprovalAlertFormat() {
            return Comments_ApprovalAlert;
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_Approve property value.
        /// </summary>
        /// <returns>The Comments_Approve property value.</returns>
        public static string Comments_ApproveFormat() {
            return Comments_Approve;
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_Comment property value.
        /// </summary>
        /// <returns>The Comments_Comment property value.</returns>
        public static string Comments_CommentFormat() {
            return Comments_Comment;
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_Comments property value.
        /// </summary>
        /// <returns>The Comments_Comments property value.</returns>
        public static string Comments_CommentsFormat() {
            return Comments_Comments;
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_ConfirmDelete property value.
        /// </summary>
        /// <returns>The Comments_ConfirmDelete property value.</returns>
        public static string Comments_ConfirmDeleteFormat() {
            return Comments_ConfirmDelete;
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_Email property value.
        /// </summary>
        /// <returns>The Comments_Email property value.</returns>
        public static string Comments_EmailFormat() {
            return Comments_Email;
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_ErrorMessage_Comments property value.
        /// </summary>
        /// <returns>The Comments_ErrorMessage_Comments property value.</returns>
        public static string Comments_ErrorMessage_CommentsFormat() {
            return Comments_ErrorMessage_Comments;
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_ErrorMessage_EmailFormat property value.
        /// </summary>
        /// <returns>The Comments_ErrorMessage_EmailFormat property value.</returns>
        public static string Comments_ErrorMessage_EmailFormatFormat() {
            return Comments_ErrorMessage_EmailFormat;
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_ErrorMessage_EmailRequired property value.
        /// </summary>
        /// <returns>The Comments_ErrorMessage_EmailRequired property value.</returns>
        public static string Comments_ErrorMessage_EmailRequiredFormat() {
            return Comments_ErrorMessage_EmailRequired;
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_ErrorMessage_Name property value.
        /// </summary>
        /// <returns>The Comments_ErrorMessage_Name property value.</returns>
        public static string Comments_ErrorMessage_NameFormat() {
            return Comments_ErrorMessage_Name;
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_ErrorMessage_UrlFormat property value.
        /// </summary>
        /// <returns>The Comments_ErrorMessage_UrlFormat property value.</returns>
        public static string Comments_ErrorMessage_UrlFormatFormat() {
            return Comments_ErrorMessage_UrlFormat;
        }
        
        /// <summary>
        /// Formats a localized string similar to '{0} has commented on {1}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Comments_MailSubjectFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, Comments_MailSubject, arg0, arg1);
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_Name property value.
        /// </summary>
        /// <returns>The Comments_Name property value.</returns>
        public static string Comments_NameFormat() {
            return Comments_Name;
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_Notify property value.
        /// </summary>
        /// <returns>The Comments_Notify property value.</returns>
        public static string Comments_NotifyFormat() {
            return Comments_Notify;
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_ReportHam property value.
        /// </summary>
        /// <returns>The Comments_ReportHam property value.</returns>
        public static string Comments_ReportHamFormat() {
            return Comments_ReportHam;
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_ReportSpam property value.
        /// </summary>
        /// <returns>The Comments_ReportSpam property value.</returns>
        public static string Comments_ReportSpamFormat() {
            return Comments_ReportSpam;
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_Save property value.
        /// </summary>
        /// <returns>The Comments_Save property value.</returns>
        public static string Comments_SaveFormat() {
            return Comments_Save;
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_Sender_Url property value.
        /// </summary>
        /// <returns>The Comments_Sender_Url property value.</returns>
        public static string Comments_Sender_UrlFormat() {
            return Comments_Sender_Url;
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_Url property value.
        /// </summary>
        /// <returns>The Comments_Url property value.</returns>
        public static string Comments_UrlFormat() {
            return Comments_Url;
        }
        
        /// <summary>
        /// The stub formatting method returning the Comments_ValidationSummary property value.
        /// </summary>
        /// <returns>The Comments_ValidationSummary property value.</returns>
        public static string Comments_ValidationSummaryFormat() {
            return Comments_ValidationSummary;
        }
        
        /// <summary>
        /// The stub formatting method returning the CommentsAdmin property value.
        /// </summary>
        /// <returns>The CommentsAdmin property value.</returns>
        public static string CommentsAdminFormat() {
            return CommentsAdmin;
        }
        
        /// <summary>
        /// The stub formatting method returning the ConfirmDelete property value.
        /// </summary>
        /// <returns>The ConfirmDelete property value.</returns>
        public static string ConfirmDeleteFormat() {
            return ConfirmDelete;
        }
        
        /// <summary>
        /// The stub formatting method returning the ConfirmDeleteSpam property value.
        /// </summary>
        /// <returns>The ConfirmDeleteSpam property value.</returns>
        public static string ConfirmDeleteSpamFormat() {
            return ConfirmDeleteSpam;
        }
        
        /// <summary>
        /// The stub formatting method returning the ConfirmDeleteUnapproved property value.
        /// </summary>
        /// <returns>The ConfirmDeleteUnapproved property value.</returns>
        public static string ConfirmDeleteUnapprovedFormat() {
            return ConfirmDeleteUnapproved;
        }
        
        /// <summary>
        /// The stub formatting method returning the Delete property value.
        /// </summary>
        /// <returns>The Delete property value.</returns>
        public static string DeleteFormat() {
            return Delete;
        }
        
        /// <summary>
        /// The stub formatting method returning the DeleteSpam property value.
        /// </summary>
        /// <returns>The DeleteSpam property value.</returns>
        public static string DeleteSpamFormat() {
            return DeleteSpam;
        }
        
        /// <summary>
        /// The stub formatting method returning the DeleteUnapproved property value.
        /// </summary>
        /// <returns>The DeleteUnapproved property value.</returns>
        public static string DeleteUnapprovedFormat() {
            return DeleteUnapproved;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit property value.
        /// </summary>
        /// <returns>The Edit property value.</returns>
        public static string EditFormat() {
            return Edit;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_Application property value.
        /// </summary>
        /// <returns>The Edit_Application property value.</returns>
        public static string Edit_ApplicationFormat() {
            return Edit_Application;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_Attachments property value.
        /// </summary>
        /// <returns>The Edit_Attachments property value.</returns>
        public static string Edit_AttachmentsFormat() {
            return Edit_Attachments;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_BlogTitle property value.
        /// </summary>
        /// <returns>The Edit_BlogTitle property value.</returns>
        public static string Edit_BlogTitleFormat() {
            return Edit_BlogTitle;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_Cancel property value.
        /// </summary>
        /// <returns>The Edit_Cancel property value.</returns>
        public static string Edit_CancelFormat() {
            return Edit_Cancel;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_Cancel_AccessKey property value.
        /// </summary>
        /// <returns>The Edit_Cancel_AccessKey property value.</returns>
        public static string Edit_Cancel_AccessKeyFormat() {
            return Edit_Cancel_AccessKey;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_Categories property value.
        /// </summary>
        /// <returns>The Edit_Categories property value.</returns>
        public static string Edit_CategoriesFormat() {
            return Edit_Categories;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_Content property value.
        /// </summary>
        /// <returns>The Edit_Content property value.</returns>
        public static string Edit_ContentFormat() {
            return Edit_Content;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_Description property value.
        /// </summary>
        /// <returns>The Edit_Description property value.</returns>
        public static string Edit_DescriptionFormat() {
            return Edit_Description;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_EditCategories property value.
        /// </summary>
        /// <returns>The Edit_EditCategories property value.</returns>
        public static string Edit_EditCategoriesFormat() {
            return Edit_EditCategories;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_ErrorMessage_AlreadyExits property value.
        /// </summary>
        /// <returns>The Edit_ErrorMessage_AlreadyExits property value.</returns>
        public static string Edit_ErrorMessage_AlreadyExitsFormat() {
            return Edit_ErrorMessage_AlreadyExits;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_ErrorMessage_TitleRequired property value.
        /// </summary>
        /// <returns>The Edit_ErrorMessage_TitleRequired property value.</returns>
        public static string Edit_ErrorMessage_TitleRequiredFormat() {
            return Edit_ErrorMessage_TitleRequired;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_IsCommentingAllowed property value.
        /// </summary>
        /// <returns>The Edit_IsCommentingAllowed property value.</returns>
        public static string Edit_IsCommentingAllowedFormat() {
            return Edit_IsCommentingAllowed;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_IsPublished property value.
        /// </summary>
        /// <returns>The Edit_IsPublished property value.</returns>
        public static string Edit_IsPublishedFormat() {
            return Edit_IsPublished;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_PublishDate property value.
        /// </summary>
        /// <returns>The Edit_PublishDate property value.</returns>
        public static string Edit_PublishDateFormat() {
            return Edit_PublishDate;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_Roles property value.
        /// </summary>
        /// <returns>The Edit_Roles property value.</returns>
        public static string Edit_RolesFormat() {
            return Edit_Roles;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_Save property value.
        /// </summary>
        /// <returns>The Edit_Save property value.</returns>
        public static string Edit_SaveFormat() {
            return Edit_Save;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_Save_AccessKey property value.
        /// </summary>
        /// <returns>The Edit_Save_AccessKey property value.</returns>
        public static string Edit_Save_AccessKeyFormat() {
            return Edit_Save_AccessKey;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_Tags property value.
        /// </summary>
        /// <returns>The Edit_Tags property value.</returns>
        public static string Edit_TagsFormat() {
            return Edit_Tags;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_TagTheNet property value.
        /// </summary>
        /// <returns>The Edit_TagTheNet property value.</returns>
        public static string Edit_TagTheNetFormat() {
            return Edit_TagTheNet;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_Title property value.
        /// </summary>
        /// <returns>The Edit_Title property value.</returns>
        public static string Edit_TitleFormat() {
            return Edit_Title;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_ValidationSummary property value.
        /// </summary>
        /// <returns>The Edit_ValidationSummary property value.</returns>
        public static string Edit_ValidationSummaryFormat() {
            return Edit_ValidationSummary;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit_Yahoo property value.
        /// </summary>
        /// <returns>The Edit_Yahoo property value.</returns>
        public static string Edit_YahooFormat() {
            return Edit_Yahoo;
        }
        
        /// <summary>
        /// The stub formatting method returning the Email property value.
        /// </summary>
        /// <returns>The Email property value.</returns>
        public static string EmailFormat() {
            return Email;
        }
        
        /// <summary>
        /// The stub formatting method returning the Home property value.
        /// </summary>
        /// <returns>The Home property value.</returns>
        public static string HomeFormat() {
            return Home;
        }
        
        /// <summary>
        /// The stub formatting method returning the InvitationText property value.
        /// </summary>
        /// <returns>The InvitationText property value.</returns>
        public static string InvitationTextFormat() {
            return InvitationText;
        }
        
        /// <summary>
        /// The stub formatting method returning the NoBlogPostsWarning property value.
        /// </summary>
        /// <returns>The NoBlogPostsWarning property value.</returns>
        public static string NoBlogPostsWarningFormat() {
            return NoBlogPostsWarning;
        }
        
        /// <summary>
        /// The stub formatting method returning the NoRatingText property value.
        /// </summary>
        /// <returns>The NoRatingText property value.</returns>
        public static string NoRatingTextFormat() {
            return NoRatingText;
        }
        
        /// <summary>
        /// The stub formatting method returning the OtherArticlesByAuthor property value.
        /// </summary>
        /// <returns>The OtherArticlesByAuthor property value.</returns>
        public static string OtherArticlesByAuthorFormat() {
            return OtherArticlesByAuthor;
        }
        
        /// <summary>
        /// The stub formatting method returning the PostCannotBeFound property value.
        /// </summary>
        /// <returns>The PostCannotBeFound property value.</returns>
        public static string PostCannotBeFoundFormat() {
            return PostCannotBeFound;
        }
        
        /// <summary>
        /// The stub formatting method returning the Publish property value.
        /// </summary>
        /// <returns>The Publish property value.</returns>
        public static string PublishFormat() {
            return Publish;
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Currently rated {0:f2} by {1} visitor(s)'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string RatingTextFormat(object arg0, object arg1) {
            return string.Format(_resourceCulture, RatingText, arg0, arg1);
        }
        
        /// <summary>
        /// The stub formatting method returning the RelatedContent property value.
        /// </summary>
        /// <returns>The RelatedContent property value.</returns>
        public static string RelatedContentFormat() {
            return RelatedContent;
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Posts with keyword(s): {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string SearchDescriptionFormatStringFormat(object arg0) {
            return string.Format(_resourceCulture, SearchDescriptionFormatString, arg0);
        }
        
        /// <summary>
        /// The stub formatting method returning the Settings_EditorsTooltip property value.
        /// </summary>
        /// <returns>The Settings_EditorsTooltip property value.</returns>
        public static string Settings_EditorsTooltipFormat() {
            return Settings_EditorsTooltip;
        }
        
        /// <summary>
        /// The stub formatting method returning the Spam property value.
        /// </summary>
        /// <returns>The Spam property value.</returns>
        public static string SpamFormat() {
            return Spam;
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Posts tagged with {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string TagDescriptionFormatStringFormat(object arg0) {
            return string.Format(_resourceCulture, TagDescriptionFormatString, arg0);
        }
        
        /// <summary>
        /// The stub formatting method returning the Tags property value.
        /// </summary>
        /// <returns>The Tags property value.</returns>
        public static string TagsFormat() {
            return Tags;
        }
        
        /// <summary>
        /// The stub formatting method returning the Unapproved property value.
        /// </summary>
        /// <returns>The Unapproved property value.</returns>
        public static string UnapprovedFormat() {
            return Unapproved;
        }
        
        /// <summary>
        /// The stub formatting method returning the Unpublish property value.
        /// </summary>
        /// <returns>The Unpublish property value.</returns>
        public static string UnpublishFormat() {
            return Unpublish;
        }
        
        /// <summary>
        /// The stub formatting method returning the Unpublished property value.
        /// </summary>
        /// <returns>The Unpublished property value.</returns>
        public static string UnpublishedFormat() {
            return Unpublished;
        }
    }
}
