//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoSoftware.MonoX.Resources {
    using System;
    using System.Web.Configuration;
    using MonoSoftware.Web.ResourceProviderModel;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorProviderModel custom tool. (Mono Wrapper based on Dmytro Kryvko builder)
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorProviderModel custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2013 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MonoSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "4.7.40.4282")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class GlobalText {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalText() {
        }
        
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            System.Threading.Interlocked.Exchange(ref _resourceManager, MonoSoftware.Web.ResourceProviderModel.ResourceManagerProvider.GetResourceManager("MonoSoftware.MonoX.MonoX.Resources.GlobalText", typeof(GlobalText).Assembly));
                        }
                    }
                    finally {
                        System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'By'.
        /// </summary>
        public static string By_PropertyName {
            get {
                return "By";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'by'.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'CacheTime'.
        /// </summary>
        public static string CacheTime_PropertyName {
            get {
                return "CacheTime";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Cached for {0} seconds.'.
        /// </summary>
        public static string CacheTime {
            get {
                return ResourceManager.GetString("CacheTime", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Cancel'.
        /// </summary>
        public static string Cancel_PropertyName {
            get {
                return "Cancel";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Cancel'.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Close'.
        /// </summary>
        public static string Close_PropertyName {
            get {
                return "Close";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Close'.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Confirmation_FriendshipRelationshipExists'.
        /// </summary>
        public static string Confirmation_FriendshipRelationshipExists_PropertyName {
            get {
                return "Confirmation_FriendshipRelationshipExists";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'This request was already approved on {DateTime}.'.
        /// </summary>
        public static string Confirmation_FriendshipRelationshipExists {
            get {
                return ResourceManager.GetString("Confirmation_FriendshipRelationshipExists", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Confirmation_FriendshipRequestSuccess'.
        /// </summary>
        public static string Confirmation_FriendshipRequestSuccess_PropertyName {
            get {
                return "Confirmation_FriendshipRequestSuccess";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Request approved!'.
        /// </summary>
        public static string Confirmation_FriendshipRequestSuccess {
            get {
                return ResourceManager.GetString("Confirmation_FriendshipRequestSuccess", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Confirmation_FriendshipRequestSuccessDescription'.
        /// </summary>
        public static string Confirmation_FriendshipRequestSuccessDescription_PropertyName {
            get {
                return "Confirmation_FriendshipRequestSuccessDescription";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'You have successfully added {FriendName} to your list of friends. '.
        /// </summary>
        public static string Confirmation_FriendshipRequestSuccessDescription {
            get {
                return ResourceManager.GetString("Confirmation_FriendshipRequestSuccessDescription", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Confirmation_GeneralErrorMessage'.
        /// </summary>
        public static string Confirmation_GeneralErrorMessage_PropertyName {
            get {
                return "Confirmation_GeneralErrorMessage";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'This is not a valid request. Please make sure that you entered a correct address and try again.'.
        /// </summary>
        public static string Confirmation_GeneralErrorMessage {
            get {
                return ResourceManager.GetString("Confirmation_GeneralErrorMessage", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Confirmation_GroupAlreadyMember'.
        /// </summary>
        public static string Confirmation_GroupAlreadyMember_PropertyName {
            get {
                return "Confirmation_GroupAlreadyMember";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'This request was already approved on {DateTime}.'.
        /// </summary>
        public static string Confirmation_GroupAlreadyMember {
            get {
                return ResourceManager.GetString("Confirmation_GroupAlreadyMember", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Confirmation_GroupRequestSuccess'.
        /// </summary>
        public static string Confirmation_GroupRequestSuccess_PropertyName {
            get {
                return "Confirmation_GroupRequestSuccess";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Request approved!'.
        /// </summary>
        public static string Confirmation_GroupRequestSuccess {
            get {
                return ResourceManager.GetString("Confirmation_GroupRequestSuccess", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Confirmation_GroupRequestSuccessDescription'.
        /// </summary>
        public static string Confirmation_GroupRequestSuccessDescription_PropertyName {
            get {
                return "Confirmation_GroupRequestSuccessDescription";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'You have been successfully added to the group &lt;a title=&apos;{GroupName}&apos; href=&apos;{GroupUrl}&apos;&gt;{GroupName}&lt;/a&gt;. '.
        /// </summary>
        public static string Confirmation_GroupRequestSuccessDescription {
            get {
                return ResourceManager.GetString("Confirmation_GroupRequestSuccessDescription", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Confirmation_RequestErrorText'.
        /// </summary>
        public static string Confirmation_RequestErrorText_PropertyName {
            get {
                return "Confirmation_RequestErrorText";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Your request was not processed successfully. Please contact support for more information.'.
        /// </summary>
        public static string Confirmation_RequestErrorText {
            get {
                return ResourceManager.GetString("Confirmation_RequestErrorText", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Confirmation_RequestErrorTitle'.
        /// </summary>
        public static string Confirmation_RequestErrorTitle_PropertyName {
            get {
                return "Confirmation_RequestErrorTitle";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'An error has occured!'.
        /// </summary>
        public static string Confirmation_RequestErrorTitle {
            get {
                return ResourceManager.GetString("Confirmation_RequestErrorTitle", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Copy'.
        /// </summary>
        public static string Copy_PropertyName {
            get {
                return "Copy";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Copy'.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Cut'.
        /// </summary>
        public static string Cut_PropertyName {
            get {
                return "Cut";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Cut'.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Delete'.
        /// </summary>
        public static string Delete_PropertyName {
            get {
                return "Delete";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Delete'.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'DeleteConfirmation'.
        /// </summary>
        public static string DeleteConfirmation_PropertyName {
            get {
                return "DeleteConfirmation";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'This item will be deleted. Are you sure?'.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Description'.
        /// </summary>
        public static string Description_PropertyName {
            get {
                return "Description";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Description'.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Edit'.
        /// </summary>
        public static string Edit_PropertyName {
            get {
                return "Edit";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Edit'.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EmailNoReply'.
        /// </summary>
        public static string EmailNoReply_PropertyName {
            get {
                return "EmailNoReply";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Please, do not reply to this e-mail.'.
        /// </summary>
        public static string EmailNoReply {
            get {
                return ResourceManager.GetString("EmailNoReply", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Error'.
        /// </summary>
        public static string Error_PropertyName {
            get {
                return "Error";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error'.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'First'.
        /// </summary>
        public static string First_PropertyName {
            get {
                return "First";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'First'.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'From'.
        /// </summary>
        public static string From_PropertyName {
            get {
                return "From";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'From'.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Insert'.
        /// </summary>
        public static string Insert_PropertyName {
            get {
                return "Insert";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Insert'.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Last'.
        /// </summary>
        public static string Last_PropertyName {
            get {
                return "Last";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Last'.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'MailSendError'.
        /// </summary>
        public static string MailSendError_PropertyName {
            get {
                return "MailSendError";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Your message was not sent.'.
        /// </summary>
        public static string MailSendError {
            get {
                return ResourceManager.GetString("MailSendError", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'MailSendSuccess'.
        /// </summary>
        public static string MailSendSuccess_PropertyName {
            get {
                return "MailSendSuccess";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Success'.
        /// </summary>
        public static string MailSendSuccess {
            get {
                return ResourceManager.GetString("MailSendSuccess", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'MoveDown'.
        /// </summary>
        public static string MoveDown_PropertyName {
            get {
                return "MoveDown";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Move down'.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'MoveUp'.
        /// </summary>
        public static string MoveUp_PropertyName {
            get {
                return "MoveUp";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Move up'.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Name'.
        /// </summary>
        public static string Name_PropertyName {
            get {
                return "Name";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Name'.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'New'.
        /// </summary>
        public static string New_PropertyName {
            get {
                return "New";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'New'.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'NewFolder'.
        /// </summary>
        public static string NewFolder_PropertyName {
            get {
                return "NewFolder";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'New folder'.
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'NewPage'.
        /// </summary>
        public static string NewPage_PropertyName {
            get {
                return "NewPage";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'New page'.
        /// </summary>
        public static string NewPage {
            get {
                return ResourceManager.GetString("NewPage", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Next'.
        /// </summary>
        public static string Next_PropertyName {
            get {
                return "Next";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Next'.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'NextGroup'.
        /// </summary>
        public static string NextGroup_PropertyName {
            get {
                return "NextGroup";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Next group'.
        /// </summary>
        public static string NextGroup {
            get {
                return ResourceManager.GetString("NextGroup", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'No'.
        /// </summary>
        public static string No_PropertyName {
            get {
                return "No";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'No'.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'NoActionPermissions'.
        /// </summary>
        public static string NoActionPermissions_PropertyName {
            get {
                return "NoActionPermissions";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'You don&apos;t have permissions for this action.'.
        /// </summary>
        public static string NoActionPermissions {
            get {
                return ResourceManager.GetString("NoActionPermissions", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'NoPreference'.
        /// </summary>
        public static string NoPreference_PropertyName {
            get {
                return "NoPreference";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Please select'.
        /// </summary>
        public static string NoPreference {
            get {
                return ResourceManager.GetString("NoPreference", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Of'.
        /// </summary>
        public static string Of_PropertyName {
            get {
                return "Of";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Of'.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'OK'.
        /// </summary>
        public static string OK_PropertyName {
            get {
                return "OK";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'OK'.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Open'.
        /// </summary>
        public static string Open_PropertyName {
            get {
                return "Open";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Open'.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Page'.
        /// </summary>
        public static string Page_PropertyName {
            get {
                return "Page";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Page'.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageProperties'.
        /// </summary>
        public static string PageProperties_PropertyName {
            get {
                return "PageProperties";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Page properties'.
        /// </summary>
        public static string PageProperties {
            get {
                return ResourceManager.GetString("PageProperties", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Paste'.
        /// </summary>
        public static string Paste_PropertyName {
            get {
                return "Paste";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Paste'.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PasteAfter'.
        /// </summary>
        public static string PasteAfter_PropertyName {
            get {
                return "PasteAfter";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Paste after'.
        /// </summary>
        public static string PasteAfter {
            get {
                return ResourceManager.GetString("PasteAfter", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PasteBefore'.
        /// </summary>
        public static string PasteBefore_PropertyName {
            get {
                return "PasteBefore";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Paste before'.
        /// </summary>
        public static string PasteBefore {
            get {
                return ResourceManager.GetString("PasteBefore", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PoweredByMonoX'.
        /// </summary>
        public static string PoweredByMonoX_PropertyName {
            get {
                return "PoweredByMonoX";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Powered by Mono Software MonoX CMS for ASP.NET.'.
        /// </summary>
        public static string PoweredByMonoX {
            get {
                return ResourceManager.GetString("PoweredByMonoX", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Previous'.
        /// </summary>
        public static string Previous_PropertyName {
            get {
                return "Previous";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Previous'.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PreviousGroup'.
        /// </summary>
        public static string PreviousGroup_PropertyName {
            get {
                return "PreviousGroup";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Previous group'.
        /// </summary>
        public static string PreviousGroup {
            get {
                return ResourceManager.GetString("PreviousGroup", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Properties'.
        /// </summary>
        public static string Properties_PropertyName {
            get {
                return "Properties";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Properties'.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Rename'.
        /// </summary>
        public static string Rename_PropertyName {
            get {
                return "Rename";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rename'.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'ReOpen'.
        /// </summary>
        public static string ReOpen_PropertyName {
            get {
                return "ReOpen";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Reopen'.
        /// </summary>
        public static string ReOpen {
            get {
                return ResourceManager.GetString("ReOpen", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Roles'.
        /// </summary>
        public static string Roles_PropertyName {
            get {
                return "Roles";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Roles'.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Save'.
        /// </summary>
        public static string Save_PropertyName {
            get {
                return "Save";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Save'.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'test'.
        /// </summary>
        public static string test_PropertyName {
            get {
                return "test";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'test'.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Title'.
        /// </summary>
        public static string Title_PropertyName {
            get {
                return "Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Title'.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Update'.
        /// </summary>
        public static string Update_PropertyName {
            get {
                return "Update";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Update'.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Upload'.
        /// </summary>
        public static string Upload_PropertyName {
            get {
                return "Upload";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Upload'.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'ValidationSummary_HeaderText'.
        /// </summary>
        public static string ValidationSummary_HeaderText_PropertyName {
            get {
                return "ValidationSummary_HeaderText";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The following issues have to be resolved before you can proceed:'.
        /// </summary>
        public static string ValidationSummary_HeaderText {
            get {
                return ResourceManager.GetString("ValidationSummary_HeaderText", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'View'.
        /// </summary>
        public static string View_PropertyName {
            get {
                return "View";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'View'.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Yes'.
        /// </summary>
        public static string Yes_PropertyName {
            get {
                return "Yes";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Yes'.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", _resourceCulture);
            }
        }
        
        /// <summary>
        /// The stub formatting method returning the By property value.
        /// </summary>
        /// <returns>The By property value.</returns>
        public static string ByFormat() {
            return By;
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Cached for {0} seconds.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string CacheTimeFormat(object arg0) {
            return string.Format(_resourceCulture, CacheTime, arg0);
        }
        
        /// <summary>
        /// The stub formatting method returning the Cancel property value.
        /// </summary>
        /// <returns>The Cancel property value.</returns>
        public static string CancelFormat() {
            return Cancel;
        }
        
        /// <summary>
        /// The stub formatting method returning the Close property value.
        /// </summary>
        /// <returns>The Close property value.</returns>
        public static string CloseFormat() {
            return Close;
        }
        
        /// <summary>
        /// The stub formatting method returning the Confirmation_FriendshipRequestSuccess property value.
        /// </summary>
        /// <returns>The Confirmation_FriendshipRequestSuccess property value.</returns>
        public static string Confirmation_FriendshipRequestSuccessFormat() {
            return Confirmation_FriendshipRequestSuccess;
        }
        
        /// <summary>
        /// The stub formatting method returning the Confirmation_GeneralErrorMessage property value.
        /// </summary>
        /// <returns>The Confirmation_GeneralErrorMessage property value.</returns>
        public static string Confirmation_GeneralErrorMessageFormat() {
            return Confirmation_GeneralErrorMessage;
        }
        
        /// <summary>
        /// The stub formatting method returning the Confirmation_GroupRequestSuccess property value.
        /// </summary>
        /// <returns>The Confirmation_GroupRequestSuccess property value.</returns>
        public static string Confirmation_GroupRequestSuccessFormat() {
            return Confirmation_GroupRequestSuccess;
        }
        
        /// <summary>
        /// The stub formatting method returning the Confirmation_RequestErrorText property value.
        /// </summary>
        /// <returns>The Confirmation_RequestErrorText property value.</returns>
        public static string Confirmation_RequestErrorTextFormat() {
            return Confirmation_RequestErrorText;
        }
        
        /// <summary>
        /// The stub formatting method returning the Confirmation_RequestErrorTitle property value.
        /// </summary>
        /// <returns>The Confirmation_RequestErrorTitle property value.</returns>
        public static string Confirmation_RequestErrorTitleFormat() {
            return Confirmation_RequestErrorTitle;
        }
        
        /// <summary>
        /// The stub formatting method returning the Copy property value.
        /// </summary>
        /// <returns>The Copy property value.</returns>
        public static string CopyFormat() {
            return Copy;
        }
        
        /// <summary>
        /// The stub formatting method returning the Cut property value.
        /// </summary>
        /// <returns>The Cut property value.</returns>
        public static string CutFormat() {
            return Cut;
        }
        
        /// <summary>
        /// The stub formatting method returning the Delete property value.
        /// </summary>
        /// <returns>The Delete property value.</returns>
        public static string DeleteFormat() {
            return Delete;
        }
        
        /// <summary>
        /// The stub formatting method returning the DeleteConfirmation property value.
        /// </summary>
        /// <returns>The DeleteConfirmation property value.</returns>
        public static string DeleteConfirmationFormat() {
            return DeleteConfirmation;
        }
        
        /// <summary>
        /// The stub formatting method returning the Description property value.
        /// </summary>
        /// <returns>The Description property value.</returns>
        public static string DescriptionFormat() {
            return Description;
        }
        
        /// <summary>
        /// The stub formatting method returning the Edit property value.
        /// </summary>
        /// <returns>The Edit property value.</returns>
        public static string EditFormat() {
            return Edit;
        }
        
        /// <summary>
        /// The stub formatting method returning the EmailNoReply property value.
        /// </summary>
        /// <returns>The EmailNoReply property value.</returns>
        public static string EmailNoReplyFormat() {
            return EmailNoReply;
        }
        
        /// <summary>
        /// The stub formatting method returning the Error property value.
        /// </summary>
        /// <returns>The Error property value.</returns>
        public static string ErrorFormat() {
            return Error;
        }
        
        /// <summary>
        /// The stub formatting method returning the First property value.
        /// </summary>
        /// <returns>The First property value.</returns>
        public static string FirstFormat() {
            return First;
        }
        
        /// <summary>
        /// The stub formatting method returning the From property value.
        /// </summary>
        /// <returns>The From property value.</returns>
        public static string FromFormat() {
            return From;
        }
        
        /// <summary>
        /// The stub formatting method returning the Insert property value.
        /// </summary>
        /// <returns>The Insert property value.</returns>
        public static string InsertFormat() {
            return Insert;
        }
        
        /// <summary>
        /// The stub formatting method returning the Last property value.
        /// </summary>
        /// <returns>The Last property value.</returns>
        public static string LastFormat() {
            return Last;
        }
        
        /// <summary>
        /// The stub formatting method returning the MailSendError property value.
        /// </summary>
        /// <returns>The MailSendError property value.</returns>
        public static string MailSendErrorFormat() {
            return MailSendError;
        }
        
        /// <summary>
        /// The stub formatting method returning the MailSendSuccess property value.
        /// </summary>
        /// <returns>The MailSendSuccess property value.</returns>
        public static string MailSendSuccessFormat() {
            return MailSendSuccess;
        }
        
        /// <summary>
        /// The stub formatting method returning the MoveDown property value.
        /// </summary>
        /// <returns>The MoveDown property value.</returns>
        public static string MoveDownFormat() {
            return MoveDown;
        }
        
        /// <summary>
        /// The stub formatting method returning the MoveUp property value.
        /// </summary>
        /// <returns>The MoveUp property value.</returns>
        public static string MoveUpFormat() {
            return MoveUp;
        }
        
        /// <summary>
        /// The stub formatting method returning the Name property value.
        /// </summary>
        /// <returns>The Name property value.</returns>
        public static string NameFormat() {
            return Name;
        }
        
        /// <summary>
        /// The stub formatting method returning the New property value.
        /// </summary>
        /// <returns>The New property value.</returns>
        public static string NewFormat() {
            return New;
        }
        
        /// <summary>
        /// The stub formatting method returning the NewFolder property value.
        /// </summary>
        /// <returns>The NewFolder property value.</returns>
        public static string NewFolderFormat() {
            return NewFolder;
        }
        
        /// <summary>
        /// The stub formatting method returning the NewPage property value.
        /// </summary>
        /// <returns>The NewPage property value.</returns>
        public static string NewPageFormat() {
            return NewPage;
        }
        
        /// <summary>
        /// The stub formatting method returning the Next property value.
        /// </summary>
        /// <returns>The Next property value.</returns>
        public static string NextFormat() {
            return Next;
        }
        
        /// <summary>
        /// The stub formatting method returning the NextGroup property value.
        /// </summary>
        /// <returns>The NextGroup property value.</returns>
        public static string NextGroupFormat() {
            return NextGroup;
        }
        
        /// <summary>
        /// The stub formatting method returning the No property value.
        /// </summary>
        /// <returns>The No property value.</returns>
        public static string NoFormat() {
            return No;
        }
        
        /// <summary>
        /// The stub formatting method returning the NoActionPermissions property value.
        /// </summary>
        /// <returns>The NoActionPermissions property value.</returns>
        public static string NoActionPermissionsFormat() {
            return NoActionPermissions;
        }
        
        /// <summary>
        /// The stub formatting method returning the NoPreference property value.
        /// </summary>
        /// <returns>The NoPreference property value.</returns>
        public static string NoPreferenceFormat() {
            return NoPreference;
        }
        
        /// <summary>
        /// The stub formatting method returning the Of property value.
        /// </summary>
        /// <returns>The Of property value.</returns>
        public static string OfFormat() {
            return Of;
        }
        
        /// <summary>
        /// The stub formatting method returning the OK property value.
        /// </summary>
        /// <returns>The OK property value.</returns>
        public static string OKFormat() {
            return OK;
        }
        
        /// <summary>
        /// The stub formatting method returning the Open property value.
        /// </summary>
        /// <returns>The Open property value.</returns>
        public static string OpenFormat() {
            return Open;
        }
        
        /// <summary>
        /// The stub formatting method returning the Page property value.
        /// </summary>
        /// <returns>The Page property value.</returns>
        public static string PageFormat() {
            return Page;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageProperties property value.
        /// </summary>
        /// <returns>The PageProperties property value.</returns>
        public static string PagePropertiesFormat() {
            return PageProperties;
        }
        
        /// <summary>
        /// The stub formatting method returning the Paste property value.
        /// </summary>
        /// <returns>The Paste property value.</returns>
        public static string PasteFormat() {
            return Paste;
        }
        
        /// <summary>
        /// The stub formatting method returning the PasteAfter property value.
        /// </summary>
        /// <returns>The PasteAfter property value.</returns>
        public static string PasteAfterFormat() {
            return PasteAfter;
        }
        
        /// <summary>
        /// The stub formatting method returning the PasteBefore property value.
        /// </summary>
        /// <returns>The PasteBefore property value.</returns>
        public static string PasteBeforeFormat() {
            return PasteBefore;
        }
        
        /// <summary>
        /// The stub formatting method returning the PoweredByMonoX property value.
        /// </summary>
        /// <returns>The PoweredByMonoX property value.</returns>
        public static string PoweredByMonoXFormat() {
            return PoweredByMonoX;
        }
        
        /// <summary>
        /// The stub formatting method returning the Previous property value.
        /// </summary>
        /// <returns>The Previous property value.</returns>
        public static string PreviousFormat() {
            return Previous;
        }
        
        /// <summary>
        /// The stub formatting method returning the PreviousGroup property value.
        /// </summary>
        /// <returns>The PreviousGroup property value.</returns>
        public static string PreviousGroupFormat() {
            return PreviousGroup;
        }
        
        /// <summary>
        /// The stub formatting method returning the Properties property value.
        /// </summary>
        /// <returns>The Properties property value.</returns>
        public static string PropertiesFormat() {
            return Properties;
        }
        
        /// <summary>
        /// The stub formatting method returning the Rename property value.
        /// </summary>
        /// <returns>The Rename property value.</returns>
        public static string RenameFormat() {
            return Rename;
        }
        
        /// <summary>
        /// The stub formatting method returning the ReOpen property value.
        /// </summary>
        /// <returns>The ReOpen property value.</returns>
        public static string ReOpenFormat() {
            return ReOpen;
        }
        
        /// <summary>
        /// The stub formatting method returning the Roles property value.
        /// </summary>
        /// <returns>The Roles property value.</returns>
        public static string RolesFormat() {
            return Roles;
        }
        
        /// <summary>
        /// The stub formatting method returning the Save property value.
        /// </summary>
        /// <returns>The Save property value.</returns>
        public static string SaveFormat() {
            return Save;
        }
        
        /// <summary>
        /// The stub formatting method returning the test property value.
        /// </summary>
        /// <returns>The test property value.</returns>
        public static string testFormat() {
            return test;
        }
        
        /// <summary>
        /// The stub formatting method returning the Title property value.
        /// </summary>
        /// <returns>The Title property value.</returns>
        public static string TitleFormat() {
            return Title;
        }
        
        /// <summary>
        /// The stub formatting method returning the Update property value.
        /// </summary>
        /// <returns>The Update property value.</returns>
        public static string UpdateFormat() {
            return Update;
        }
        
        /// <summary>
        /// The stub formatting method returning the Upload property value.
        /// </summary>
        /// <returns>The Upload property value.</returns>
        public static string UploadFormat() {
            return Upload;
        }
        
        /// <summary>
        /// The stub formatting method returning the ValidationSummary_HeaderText property value.
        /// </summary>
        /// <returns>The ValidationSummary_HeaderText property value.</returns>
        public static string ValidationSummary_HeaderTextFormat() {
            return ValidationSummary_HeaderText;
        }
        
        /// <summary>
        /// The stub formatting method returning the View property value.
        /// </summary>
        /// <returns>The View property value.</returns>
        public static string ViewFormat() {
            return View;
        }
        
        /// <summary>
        /// The stub formatting method returning the Yes property value.
        /// </summary>
        /// <returns>The Yes property value.</returns>
        public static string YesFormat() {
            return Yes;
        }
    }
}
