//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoSoftware.MonoX.Resources {
    using System;
    using System.Web.Configuration;
    using MonoSoftware.Web.ResourceProviderModel;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorProviderModel custom tool. (Mono Wrapper based on Dmytro Kryvko builder)
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorProviderModel custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2013 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MonoSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "4.7.40.4282")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class PageResources {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageResources() {
        }
        
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            System.Threading.Interlocked.Exchange(ref _resourceManager, MonoSoftware.Web.ResourceProviderModel.ResourceManagerProvider.GetResourceManager("MonoSoftware.MonoX.MonoX.Resources.PageResources", typeof(PageResources).Assembly));
                        }
                    }
                    finally {
                        System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Confirmation_Title'.
        /// </summary>
        public static string Confirmation_Title_PropertyName {
            get {
                return "Confirmation_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Confirmation'.
        /// </summary>
        public static string Confirmation_Title {
            get {
                return ResourceManager.GetString("Confirmation_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Dashboard_Title'.
        /// </summary>
        public static string Dashboard_Title_PropertyName {
            get {
                return "Dashboard_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Social Networking'.
        /// </summary>
        public static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Discussion_Title'.
        /// </summary>
        public static string Discussion_Title_PropertyName {
            get {
                return "Discussion_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Discussion'.
        /// </summary>
        public static string Discussion_Title {
            get {
                return ResourceManager.GetString("Discussion_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'FileView_Title'.
        /// </summary>
        public static string FileView_Title_PropertyName {
            get {
                return "FileView_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'File view'.
        /// </summary>
        public static string FileView_Title {
            get {
                return ResourceManager.GetString("FileView_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Groups_GroupContainer'.
        /// </summary>
        public static string Groups_GroupContainer_PropertyName {
            get {
                return "Groups_GroupContainer";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Groups'.
        /// </summary>
        public static string Groups_GroupContainer {
            get {
                return ResourceManager.GetString("Groups_GroupContainer", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Groups_GroupInfo'.
        /// </summary>
        public static string Groups_GroupInfo_PropertyName {
            get {
                return "Groups_GroupInfo";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Group info'.
        /// </summary>
        public static string Groups_GroupInfo {
            get {
                return ResourceManager.GetString("Groups_GroupInfo", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Groups_GroupMembers'.
        /// </summary>
        public static string Groups_GroupMembers_PropertyName {
            get {
                return "Groups_GroupMembers";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Group members'.
        /// </summary>
        public static string Groups_GroupMembers {
            get {
                return ResourceManager.GetString("Groups_GroupMembers", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Groups_InvitationsReceived'.
        /// </summary>
        public static string Groups_InvitationsReceived_PropertyName {
            get {
                return "Groups_InvitationsReceived";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Request received'.
        /// </summary>
        public static string Groups_InvitationsReceived {
            get {
                return ResourceManager.GetString("Groups_InvitationsReceived", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Groups_InvitationsSent'.
        /// </summary>
        public static string Groups_InvitationsSent_PropertyName {
            get {
                return "Groups_InvitationsSent";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Sent invitations'.
        /// </summary>
        public static string Groups_InvitationsSent {
            get {
                return ResourceManager.GetString("Groups_InvitationsSent", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Groups_SearchGroups'.
        /// </summary>
        public static string Groups_SearchGroups_PropertyName {
            get {
                return "Groups_SearchGroups";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Search groups'.
        /// </summary>
        public static string Groups_SearchGroups {
            get {
                return ResourceManager.GetString("Groups_SearchGroups", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Groups_SearchGroups_DefaultSearchText'.
        /// </summary>
        public static string Groups_SearchGroups_DefaultSearchText_PropertyName {
            get {
                return "Groups_SearchGroups_DefaultSearchText";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Enter group search keywords'.
        /// </summary>
        public static string Groups_SearchGroups_DefaultSearchText {
            get {
                return ResourceManager.GetString("Groups_SearchGroups_DefaultSearchText", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Groups_Title'.
        /// </summary>
        public static string Groups_Title_PropertyName {
            get {
                return "Groups_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'User groups'.
        /// </summary>
        public static string Groups_Title {
            get {
                return ResourceManager.GetString("Groups_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Label_Blogs'.
        /// </summary>
        public static string Label_Blogs_PropertyName {
            get {
                return "Label_Blogs";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Blogs'.
        /// </summary>
        public static string Label_Blogs {
            get {
                return ResourceManager.GetString("Label_Blogs", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Label_BlogSearch'.
        /// </summary>
        public static string Label_BlogSearch_PropertyName {
            get {
                return "Label_BlogSearch";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Enter blog search terms'.
        /// </summary>
        public static string Label_BlogSearch {
            get {
                return ResourceManager.GetString("Label_BlogSearch", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Label_Groups'.
        /// </summary>
        public static string Label_Groups_PropertyName {
            get {
                return "Label_Groups";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Groups'.
        /// </summary>
        public static string Label_Groups {
            get {
                return ResourceManager.GetString("Label_Groups", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Label_GroupSearch'.
        /// </summary>
        public static string Label_GroupSearch_PropertyName {
            get {
                return "Label_GroupSearch";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Enter group search terms'.
        /// </summary>
        public static string Label_GroupSearch {
            get {
                return ResourceManager.GetString("Label_GroupSearch", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Label_People'.
        /// </summary>
        public static string Label_People_PropertyName {
            get {
                return "Label_People";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Users'.
        /// </summary>
        public static string Label_People {
            get {
                return ResourceManager.GetString("Label_People", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Label_PeopleSearch'.
        /// </summary>
        public static string Label_PeopleSearch_PropertyName {
            get {
                return "Label_PeopleSearch";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Enter people search terms'.
        /// </summary>
        public static string Label_PeopleSearch {
            get {
                return ResourceManager.GetString("Label_PeopleSearch", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Login_Or'.
        /// </summary>
        public static string Login_Or_PropertyName {
            get {
                return "Login_Or";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Or'.
        /// </summary>
        public static string Login_Or {
            get {
                return ResourceManager.GetString("Login_Or", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Login_RpxWarning'.
        /// </summary>
        public static string Login_RpxWarning_PropertyName {
            get {
                return "Login_RpxWarning";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'NOTE: Social login module is here for the demonstration purposes only. IT WILL NOT WORK on your domain until you properly set the target applications on other social networks as described in the documentation. '.
        /// </summary>
        public static string Login_RpxWarning {
            get {
                return ResourceManager.GetString("Login_RpxWarning", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Messages_Title'.
        /// </summary>
        public static string Messages_Title_PropertyName {
            get {
                return "Messages_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Messages'.
        /// </summary>
        public static string Messages_Title {
            get {
                return ResourceManager.GetString("Messages_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Module_Activities'.
        /// </summary>
        public static string Module_Activities_PropertyName {
            get {
                return "Module_Activities";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Activities'.
        /// </summary>
        public static string Module_Activities {
            get {
                return ResourceManager.GetString("Module_Activities", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Module_BlockedUsersList'.
        /// </summary>
        public static string Module_BlockedUsersList_PropertyName {
            get {
                return "Module_BlockedUsersList";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'My Blocked Users'.
        /// </summary>
        public static string Module_BlockedUsersList {
            get {
                return ResourceManager.GetString("Module_BlockedUsersList", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Module_BlockUser'.
        /// </summary>
        public static string Module_BlockUser_PropertyName {
            get {
                return "Module_BlockUser";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Block a User'.
        /// </summary>
        public static string Module_BlockUser {
            get {
                return ResourceManager.GetString("Module_BlockUser", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Module_Friends'.
        /// </summary>
        public static string Module_Friends_PropertyName {
            get {
                return "Module_Friends";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'My friends'.
        /// </summary>
        public static string Module_Friends {
            get {
                return ResourceManager.GetString("Module_Friends", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Module_InvitationsReceived'.
        /// </summary>
        public static string Module_InvitationsReceived_PropertyName {
            get {
                return "Module_InvitationsReceived";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'My received invitations'.
        /// </summary>
        public static string Module_InvitationsReceived {
            get {
                return ResourceManager.GetString("Module_InvitationsReceived", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Module_InvitationsSent'.
        /// </summary>
        public static string Module_InvitationsSent_PropertyName {
            get {
                return "Module_InvitationsSent";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'My sent invitations'.
        /// </summary>
        public static string Module_InvitationsSent {
            get {
                return ResourceManager.GetString("Module_InvitationsSent", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Module_Messages'.
        /// </summary>
        public static string Module_Messages_PropertyName {
            get {
                return "Module_Messages";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'My messages'.
        /// </summary>
        public static string Module_Messages {
            get {
                return ResourceManager.GetString("Module_Messages", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Module_PeopleSearch'.
        /// </summary>
        public static string Module_PeopleSearch_PropertyName {
            get {
                return "Module_PeopleSearch";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Search people'.
        /// </summary>
        public static string Module_PeopleSearch {
            get {
                return ResourceManager.GetString("Module_PeopleSearch", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Module_PhotoGallery'.
        /// </summary>
        public static string Module_PhotoGallery_PropertyName {
            get {
                return "Module_PhotoGallery";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Photo gallery'.
        /// </summary>
        public static string Module_PhotoGallery {
            get {
                return ResourceManager.GetString("Module_PhotoGallery", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Module_UserProfileAlbums'.
        /// </summary>
        public static string Module_UserProfileAlbums_PropertyName {
            get {
                return "Module_UserProfileAlbums";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '{0}&apos;s Albums'.
        /// </summary>
        public static string Module_UserProfileAlbums {
            get {
                return ResourceManager.GetString("Module_UserProfileAlbums", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Module_UserProfileFriends'.
        /// </summary>
        public static string Module_UserProfileFriends_PropertyName {
            get {
                return "Module_UserProfileFriends";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '{0}&apos;s Friends'.
        /// </summary>
        public static string Module_UserProfileFriends {
            get {
                return ResourceManager.GetString("Module_UserProfileFriends", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Module_UserProfilePhotos'.
        /// </summary>
        public static string Module_UserProfilePhotos_PropertyName {
            get {
                return "Module_UserProfilePhotos";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '{0}&apos;s Photos'.
        /// </summary>
        public static string Module_UserProfilePhotos {
            get {
                return ResourceManager.GetString("Module_UserProfilePhotos", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Module_WallNotes'.
        /// </summary>
        public static string Module_WallNotes_PropertyName {
            get {
                return "Module_WallNotes";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Wall notes'.
        /// </summary>
        public static string Module_WallNotes {
            get {
                return ResourceManager.GetString("Module_WallNotes", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'MyWall_Title'.
        /// </summary>
        public static string MyWall_Title_PropertyName {
            get {
                return "MyWall_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'My Wall'.
        /// </summary>
        public static string MyWall_Title {
            get {
                return ResourceManager.GetString("MyWall_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'News_ReadMore_Title'.
        /// </summary>
        public static string News_ReadMore_Title_PropertyName {
            get {
                return "News_ReadMore_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Read More ...'.
        /// </summary>
        public static string News_ReadMore_Title {
            get {
                return ResourceManager.GetString("News_ReadMore_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageFooter_About'.
        /// </summary>
        public static string PageFooter_About_PropertyName {
            get {
                return "PageFooter_About";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'About'.
        /// </summary>
        public static string PageFooter_About {
            get {
                return ResourceManager.GetString("PageFooter_About", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageFooter_AdditionalResources'.
        /// </summary>
        public static string PageFooter_AdditionalResources_PropertyName {
            get {
                return "PageFooter_AdditionalResources";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Additional Resources'.
        /// </summary>
        public static string PageFooter_AdditionalResources {
            get {
                return ResourceManager.GetString("PageFooter_AdditionalResources", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageFooter_ConnectWithUs'.
        /// </summary>
        public static string PageFooter_ConnectWithUs_PropertyName {
            get {
                return "PageFooter_ConnectWithUs";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Connect with us'.
        /// </summary>
        public static string PageFooter_ConnectWithUs {
            get {
                return ResourceManager.GetString("PageFooter_ConnectWithUs", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageFooter_Copyright'.
        /// </summary>
        public static string PageFooter_Copyright_PropertyName {
            get {
                return "PageFooter_Copyright";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Copyright'.
        /// </summary>
        public static string PageFooter_Copyright {
            get {
                return ResourceManager.GetString("PageFooter_Copyright", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageFooter_FacebookFan'.
        /// </summary>
        public static string PageFooter_FacebookFan_PropertyName {
            get {
                return "PageFooter_FacebookFan";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Become a fan on Facebook'.
        /// </summary>
        public static string PageFooter_FacebookFan {
            get {
                return ResourceManager.GetString("PageFooter_FacebookFan", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageFooter_GeneralInfo'.
        /// </summary>
        public static string PageFooter_GeneralInfo_PropertyName {
            get {
                return "PageFooter_GeneralInfo";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'General Info'.
        /// </summary>
        public static string PageFooter_GeneralInfo {
            get {
                return ResourceManager.GetString("PageFooter_GeneralInfo", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageFooter_Home'.
        /// </summary>
        public static string PageFooter_Home_PropertyName {
            get {
                return "PageFooter_Home";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Home'.
        /// </summary>
        public static string PageFooter_Home {
            get {
                return ResourceManager.GetString("PageFooter_Home", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageFooter_Licensing'.
        /// </summary>
        public static string PageFooter_Licensing_PropertyName {
            get {
                return "PageFooter_Licensing";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Licensing'.
        /// </summary>
        public static string PageFooter_Licensing {
            get {
                return ResourceManager.GetString("PageFooter_Licensing", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageFooter_LinkedInConnect'.
        /// </summary>
        public static string PageFooter_LinkedInConnect_PropertyName {
            get {
                return "PageFooter_LinkedInConnect";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Connect on LinkedIn'.
        /// </summary>
        public static string PageFooter_LinkedInConnect {
            get {
                return ResourceManager.GetString("PageFooter_LinkedInConnect", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageFooter_PrivacyPolicy'.
        /// </summary>
        public static string PageFooter_PrivacyPolicy_PropertyName {
            get {
                return "PageFooter_PrivacyPolicy";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Privacy policy'.
        /// </summary>
        public static string PageFooter_PrivacyPolicy {
            get {
                return ResourceManager.GetString("PageFooter_PrivacyPolicy", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageFooter_SiteMembership'.
        /// </summary>
        public static string PageFooter_SiteMembership_PropertyName {
            get {
                return "PageFooter_SiteMembership";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Site Membership'.
        /// </summary>
        public static string PageFooter_SiteMembership {
            get {
                return ResourceManager.GetString("PageFooter_SiteMembership", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageFooter_SocialNetworking'.
        /// </summary>
        public static string PageFooter_SocialNetworking_PropertyName {
            get {
                return "PageFooter_SocialNetworking";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Social Networking'.
        /// </summary>
        public static string PageFooter_SocialNetworking {
            get {
                return ResourceManager.GetString("PageFooter_SocialNetworking", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageFooter_SocialNetworkingBlog'.
        /// </summary>
        public static string PageFooter_SocialNetworkingBlog_PropertyName {
            get {
                return "PageFooter_SocialNetworkingBlog";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Blog'.
        /// </summary>
        public static string PageFooter_SocialNetworkingBlog {
            get {
                return ResourceManager.GetString("PageFooter_SocialNetworkingBlog", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageFooter_SocialNetworkingGroups'.
        /// </summary>
        public static string PageFooter_SocialNetworkingGroups_PropertyName {
            get {
                return "PageFooter_SocialNetworkingGroups";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Groups'.
        /// </summary>
        public static string PageFooter_SocialNetworkingGroups {
            get {
                return ResourceManager.GetString("PageFooter_SocialNetworkingGroups", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageFooter_SocialNetworkingHome'.
        /// </summary>
        public static string PageFooter_SocialNetworkingHome_PropertyName {
            get {
                return "PageFooter_SocialNetworkingHome";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Home'.
        /// </summary>
        public static string PageFooter_SocialNetworkingHome {
            get {
                return ResourceManager.GetString("PageFooter_SocialNetworkingHome", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageFooter_SocialNetworkingPhotos'.
        /// </summary>
        public static string PageFooter_SocialNetworkingPhotos_PropertyName {
            get {
                return "PageFooter_SocialNetworkingPhotos";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Photos'.
        /// </summary>
        public static string PageFooter_SocialNetworkingPhotos {
            get {
                return ResourceManager.GetString("PageFooter_SocialNetworkingPhotos", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageFooter_TermsOfUse'.
        /// </summary>
        public static string PageFooter_TermsOfUse_PropertyName {
            get {
                return "PageFooter_TermsOfUse";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Terms of use'.
        /// </summary>
        public static string PageFooter_TermsOfUse {
            get {
                return ResourceManager.GetString("PageFooter_TermsOfUse", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PageFooter_TwitterFollow'.
        /// </summary>
        public static string PageFooter_TwitterFollow_PropertyName {
            get {
                return "PageFooter_TwitterFollow";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Follow on Twitter'.
        /// </summary>
        public static string PageFooter_TwitterFollow {
            get {
                return ResourceManager.GetString("PageFooter_TwitterFollow", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PhotoGallery_Title'.
        /// </summary>
        public static string PhotoGallery_Title_PropertyName {
            get {
                return "PhotoGallery_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Photo gallery'.
        /// </summary>
        public static string PhotoGallery_Title {
            get {
                return ResourceManager.GetString("PhotoGallery_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Title_AdditionalResources'.
        /// </summary>
        public static string Title_AdditionalResources_PropertyName {
            get {
                return "Title_AdditionalResources";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Additional resources'.
        /// </summary>
        public static string Title_AdditionalResources {
            get {
                return ResourceManager.GetString("Title_AdditionalResources", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Title_BottomSection'.
        /// </summary>
        public static string Title_BottomSection_PropertyName {
            get {
                return "Title_BottomSection";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Bottom section'.
        /// </summary>
        public static string Title_BottomSection {
            get {
                return ResourceManager.GetString("Title_BottomSection", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Title_DescriptionOfFeatures'.
        /// </summary>
        public static string Title_DescriptionOfFeatures_PropertyName {
            get {
                return "Title_DescriptionOfFeatures";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Description of techical features'.
        /// </summary>
        public static string Title_DescriptionOfFeatures {
            get {
                return ResourceManager.GetString("Title_DescriptionOfFeatures", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Title_FeaturedProjects'.
        /// </summary>
        public static string Title_FeaturedProjects_PropertyName {
            get {
                return "Title_FeaturedProjects";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Featured projects'.
        /// </summary>
        public static string Title_FeaturedProjects {
            get {
                return ResourceManager.GetString("Title_FeaturedProjects", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Title_LeftSection'.
        /// </summary>
        public static string Title_LeftSection_PropertyName {
            get {
                return "Title_LeftSection";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Left section'.
        /// </summary>
        public static string Title_LeftSection {
            get {
                return ResourceManager.GetString("Title_LeftSection", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Title_MiddleSection'.
        /// </summary>
        public static string Title_MiddleSection_PropertyName {
            get {
                return "Title_MiddleSection";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Middle section'.
        /// </summary>
        public static string Title_MiddleSection {
            get {
                return ResourceManager.GetString("Title_MiddleSection", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Title_Resources'.
        /// </summary>
        public static string Title_Resources_PropertyName {
            get {
                return "Title_Resources";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Resources'.
        /// </summary>
        public static string Title_Resources {
            get {
                return ResourceManager.GetString("Title_Resources", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Title_RightSection'.
        /// </summary>
        public static string Title_RightSection_PropertyName {
            get {
                return "Title_RightSection";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Right section'.
        /// </summary>
        public static string Title_RightSection {
            get {
                return ResourceManager.GetString("Title_RightSection", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Title_ScreenGallery'.
        /// </summary>
        public static string Title_ScreenGallery_PropertyName {
            get {
                return "Title_ScreenGallery";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Screen Gallery'.
        /// </summary>
        public static string Title_ScreenGallery {
            get {
                return ResourceManager.GetString("Title_ScreenGallery", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Title_SearchResults'.
        /// </summary>
        public static string Title_SearchResults_PropertyName {
            get {
                return "Title_SearchResults";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Search results'.
        /// </summary>
        public static string Title_SearchResults {
            get {
                return ResourceManager.GetString("Title_SearchResults", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Title_TopSection'.
        /// </summary>
        public static string Title_TopSection_PropertyName {
            get {
                return "Title_TopSection";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Top section'.
        /// </summary>
        public static string Title_TopSection {
            get {
                return ResourceManager.GetString("Title_TopSection", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfile_DiscussionMessages_Title'.
        /// </summary>
        public static string UserProfile_DiscussionMessages_Title_PropertyName {
            get {
                return "UserProfile_DiscussionMessages_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Forum Posts'.
        /// </summary>
        public static string UserProfile_DiscussionMessages_Title {
            get {
                return ResourceManager.GetString("UserProfile_DiscussionMessages_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfile_FriendSuggestion_Title'.
        /// </summary>
        public static string UserProfile_FriendSuggestion_Title_PropertyName {
            get {
                return "UserProfile_FriendSuggestion_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'People you may know'.
        /// </summary>
        public static string UserProfile_FriendSuggestion_Title {
            get {
                return ResourceManager.GetString("UserProfile_FriendSuggestion_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfile_Map_Title'.
        /// </summary>
        public static string UserProfile_Map_Title_PropertyName {
            get {
                return "UserProfile_Map_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '{0}&apos;s Location'.
        /// </summary>
        public static string UserProfile_Map_Title {
            get {
                return ResourceManager.GetString("UserProfile_Map_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfile_NoSuchUser'.
        /// </summary>
        public static string UserProfile_NoSuchUser_PropertyName {
            get {
                return "UserProfile_NoSuchUser";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Unknown user - profile cannot be displayed.'.
        /// </summary>
        public static string UserProfile_NoSuchUser {
            get {
                return ResourceManager.GetString("UserProfile_NoSuchUser", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfile_PeopleSearch_InfoText'.
        /// </summary>
        public static string UserProfile_PeopleSearch_InfoText_PropertyName {
            get {
                return "UserProfile_PeopleSearch_InfoText";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Add this user to your list of friends.'.
        /// </summary>
        public static string UserProfile_PeopleSearch_InfoText {
            get {
                return ResourceManager.GetString("UserProfile_PeopleSearch_InfoText", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfile_PeopleSearch_Title'.
        /// </summary>
        public static string UserProfile_PeopleSearch_Title_PropertyName {
            get {
                return "UserProfile_PeopleSearch_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Invite {0}'.
        /// </summary>
        public static string UserProfile_PeopleSearch_Title {
            get {
                return ResourceManager.GetString("UserProfile_PeopleSearch_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfile_Title'.
        /// </summary>
        public static string UserProfile_Title_PropertyName {
            get {
                return "UserProfile_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'User profile for {0}'.
        /// </summary>
        public static string UserProfile_Title {
            get {
                return ResourceManager.GetString("UserProfile_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfile_UserProfile_Title'.
        /// </summary>
        public static string UserProfile_UserProfile_Title_PropertyName {
            get {
                return "UserProfile_UserProfile_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'User profile'.
        /// </summary>
        public static string UserProfile_UserProfile_Title {
            get {
                return ResourceManager.GetString("UserProfile_UserProfile_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Wall_Title'.
        /// </summary>
        public static string Wall_Title_PropertyName {
            get {
                return "Wall_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Site Wall'.
        /// </summary>
        public static string Wall_Title {
            get {
                return ResourceManager.GetString("Wall_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Wall_WallNotes_Title'.
        /// </summary>
        public static string Wall_WallNotes_Title_PropertyName {
            get {
                return "Wall_WallNotes_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Wall notes for {0}'.
        /// </summary>
        public static string Wall_WallNotes_Title {
            get {
                return ResourceManager.GetString("Wall_WallNotes_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Zone_BottomPartZone'.
        /// </summary>
        public static string Zone_BottomPartZone_PropertyName {
            get {
                return "Zone_BottomPartZone";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Bottom part zone'.
        /// </summary>
        public static string Zone_BottomPartZone {
            get {
                return ResourceManager.GetString("Zone_BottomPartZone", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Zone_ContentZone'.
        /// </summary>
        public static string Zone_ContentZone_PropertyName {
            get {
                return "Zone_ContentZone";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Content zone'.
        /// </summary>
        public static string Zone_ContentZone {
            get {
                return ResourceManager.GetString("Zone_ContentZone", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Zone_FeaturedProjectsZone'.
        /// </summary>
        public static string Zone_FeaturedProjectsZone_PropertyName {
            get {
                return "Zone_FeaturedProjectsZone";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Featured projects zone'.
        /// </summary>
        public static string Zone_FeaturedProjectsZone {
            get {
                return ResourceManager.GetString("Zone_FeaturedProjectsZone", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Zone_LeftPartZone'.
        /// </summary>
        public static string Zone_LeftPartZone_PropertyName {
            get {
                return "Zone_LeftPartZone";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Left part zone'.
        /// </summary>
        public static string Zone_LeftPartZone {
            get {
                return ResourceManager.GetString("Zone_LeftPartZone", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Zone_MiddlePartZone'.
        /// </summary>
        public static string Zone_MiddlePartZone_PropertyName {
            get {
                return "Zone_MiddlePartZone";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Middle part zone'.
        /// </summary>
        public static string Zone_MiddlePartZone {
            get {
                return ResourceManager.GetString("Zone_MiddlePartZone", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Zone_RightPartZone'.
        /// </summary>
        public static string Zone_RightPartZone_PropertyName {
            get {
                return "Zone_RightPartZone";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Right part zone'.
        /// </summary>
        public static string Zone_RightPartZone {
            get {
                return ResourceManager.GetString("Zone_RightPartZone", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Zone_SocialZone'.
        /// </summary>
        public static string Zone_SocialZone_PropertyName {
            get {
                return "Zone_SocialZone";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Social zone'.
        /// </summary>
        public static string Zone_SocialZone {
            get {
                return ResourceManager.GetString("Zone_SocialZone", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Zone_TopPartZone'.
        /// </summary>
        public static string Zone_TopPartZone_PropertyName {
            get {
                return "Zone_TopPartZone";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Top part zone'.
        /// </summary>
        public static string Zone_TopPartZone {
            get {
                return ResourceManager.GetString("Zone_TopPartZone", _resourceCulture);
            }
        }
        
        /// <summary>
        /// The stub formatting method returning the Confirmation_Title property value.
        /// </summary>
        /// <returns>The Confirmation_Title property value.</returns>
        public static string Confirmation_TitleFormat() {
            return Confirmation_Title;
        }
        
        /// <summary>
        /// The stub formatting method returning the Dashboard_Title property value.
        /// </summary>
        /// <returns>The Dashboard_Title property value.</returns>
        public static string Dashboard_TitleFormat() {
            return Dashboard_Title;
        }
        
        /// <summary>
        /// The stub formatting method returning the Discussion_Title property value.
        /// </summary>
        /// <returns>The Discussion_Title property value.</returns>
        public static string Discussion_TitleFormat() {
            return Discussion_Title;
        }
        
        /// <summary>
        /// The stub formatting method returning the FileView_Title property value.
        /// </summary>
        /// <returns>The FileView_Title property value.</returns>
        public static string FileView_TitleFormat() {
            return FileView_Title;
        }
        
        /// <summary>
        /// The stub formatting method returning the Groups_GroupContainer property value.
        /// </summary>
        /// <returns>The Groups_GroupContainer property value.</returns>
        public static string Groups_GroupContainerFormat() {
            return Groups_GroupContainer;
        }
        
        /// <summary>
        /// The stub formatting method returning the Groups_GroupInfo property value.
        /// </summary>
        /// <returns>The Groups_GroupInfo property value.</returns>
        public static string Groups_GroupInfoFormat() {
            return Groups_GroupInfo;
        }
        
        /// <summary>
        /// The stub formatting method returning the Groups_GroupMembers property value.
        /// </summary>
        /// <returns>The Groups_GroupMembers property value.</returns>
        public static string Groups_GroupMembersFormat() {
            return Groups_GroupMembers;
        }
        
        /// <summary>
        /// The stub formatting method returning the Groups_InvitationsReceived property value.
        /// </summary>
        /// <returns>The Groups_InvitationsReceived property value.</returns>
        public static string Groups_InvitationsReceivedFormat() {
            return Groups_InvitationsReceived;
        }
        
        /// <summary>
        /// The stub formatting method returning the Groups_InvitationsSent property value.
        /// </summary>
        /// <returns>The Groups_InvitationsSent property value.</returns>
        public static string Groups_InvitationsSentFormat() {
            return Groups_InvitationsSent;
        }
        
        /// <summary>
        /// The stub formatting method returning the Groups_SearchGroups property value.
        /// </summary>
        /// <returns>The Groups_SearchGroups property value.</returns>
        public static string Groups_SearchGroupsFormat() {
            return Groups_SearchGroups;
        }
        
        /// <summary>
        /// The stub formatting method returning the Groups_SearchGroups_DefaultSearchText property value.
        /// </summary>
        /// <returns>The Groups_SearchGroups_DefaultSearchText property value.</returns>
        public static string Groups_SearchGroups_DefaultSearchTextFormat() {
            return Groups_SearchGroups_DefaultSearchText;
        }
        
        /// <summary>
        /// The stub formatting method returning the Groups_Title property value.
        /// </summary>
        /// <returns>The Groups_Title property value.</returns>
        public static string Groups_TitleFormat() {
            return Groups_Title;
        }
        
        /// <summary>
        /// The stub formatting method returning the Label_Blogs property value.
        /// </summary>
        /// <returns>The Label_Blogs property value.</returns>
        public static string Label_BlogsFormat() {
            return Label_Blogs;
        }
        
        /// <summary>
        /// The stub formatting method returning the Label_BlogSearch property value.
        /// </summary>
        /// <returns>The Label_BlogSearch property value.</returns>
        public static string Label_BlogSearchFormat() {
            return Label_BlogSearch;
        }
        
        /// <summary>
        /// The stub formatting method returning the Label_Groups property value.
        /// </summary>
        /// <returns>The Label_Groups property value.</returns>
        public static string Label_GroupsFormat() {
            return Label_Groups;
        }
        
        /// <summary>
        /// The stub formatting method returning the Label_GroupSearch property value.
        /// </summary>
        /// <returns>The Label_GroupSearch property value.</returns>
        public static string Label_GroupSearchFormat() {
            return Label_GroupSearch;
        }
        
        /// <summary>
        /// The stub formatting method returning the Label_People property value.
        /// </summary>
        /// <returns>The Label_People property value.</returns>
        public static string Label_PeopleFormat() {
            return Label_People;
        }
        
        /// <summary>
        /// The stub formatting method returning the Label_PeopleSearch property value.
        /// </summary>
        /// <returns>The Label_PeopleSearch property value.</returns>
        public static string Label_PeopleSearchFormat() {
            return Label_PeopleSearch;
        }
        
        /// <summary>
        /// The stub formatting method returning the Login_Or property value.
        /// </summary>
        /// <returns>The Login_Or property value.</returns>
        public static string Login_OrFormat() {
            return Login_Or;
        }
        
        /// <summary>
        /// The stub formatting method returning the Login_RpxWarning property value.
        /// </summary>
        /// <returns>The Login_RpxWarning property value.</returns>
        public static string Login_RpxWarningFormat() {
            return Login_RpxWarning;
        }
        
        /// <summary>
        /// The stub formatting method returning the Messages_Title property value.
        /// </summary>
        /// <returns>The Messages_Title property value.</returns>
        public static string Messages_TitleFormat() {
            return Messages_Title;
        }
        
        /// <summary>
        /// The stub formatting method returning the Module_Activities property value.
        /// </summary>
        /// <returns>The Module_Activities property value.</returns>
        public static string Module_ActivitiesFormat() {
            return Module_Activities;
        }
        
        /// <summary>
        /// The stub formatting method returning the Module_BlockedUsersList property value.
        /// </summary>
        /// <returns>The Module_BlockedUsersList property value.</returns>
        public static string Module_BlockedUsersListFormat() {
            return Module_BlockedUsersList;
        }
        
        /// <summary>
        /// The stub formatting method returning the Module_BlockUser property value.
        /// </summary>
        /// <returns>The Module_BlockUser property value.</returns>
        public static string Module_BlockUserFormat() {
            return Module_BlockUser;
        }
        
        /// <summary>
        /// The stub formatting method returning the Module_Friends property value.
        /// </summary>
        /// <returns>The Module_Friends property value.</returns>
        public static string Module_FriendsFormat() {
            return Module_Friends;
        }
        
        /// <summary>
        /// The stub formatting method returning the Module_InvitationsReceived property value.
        /// </summary>
        /// <returns>The Module_InvitationsReceived property value.</returns>
        public static string Module_InvitationsReceivedFormat() {
            return Module_InvitationsReceived;
        }
        
        /// <summary>
        /// The stub formatting method returning the Module_InvitationsSent property value.
        /// </summary>
        /// <returns>The Module_InvitationsSent property value.</returns>
        public static string Module_InvitationsSentFormat() {
            return Module_InvitationsSent;
        }
        
        /// <summary>
        /// The stub formatting method returning the Module_Messages property value.
        /// </summary>
        /// <returns>The Module_Messages property value.</returns>
        public static string Module_MessagesFormat() {
            return Module_Messages;
        }
        
        /// <summary>
        /// The stub formatting method returning the Module_PeopleSearch property value.
        /// </summary>
        /// <returns>The Module_PeopleSearch property value.</returns>
        public static string Module_PeopleSearchFormat() {
            return Module_PeopleSearch;
        }
        
        /// <summary>
        /// The stub formatting method returning the Module_PhotoGallery property value.
        /// </summary>
        /// <returns>The Module_PhotoGallery property value.</returns>
        public static string Module_PhotoGalleryFormat() {
            return Module_PhotoGallery;
        }
        
        /// <summary>
        /// Formats a localized string similar to '{0}&apos;s Albums'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Module_UserProfileAlbumsFormat(object arg0) {
            return string.Format(_resourceCulture, Module_UserProfileAlbums, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to '{0}&apos;s Friends'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Module_UserProfileFriendsFormat(object arg0) {
            return string.Format(_resourceCulture, Module_UserProfileFriends, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to '{0}&apos;s Photos'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Module_UserProfilePhotosFormat(object arg0) {
            return string.Format(_resourceCulture, Module_UserProfilePhotos, arg0);
        }
        
        /// <summary>
        /// The stub formatting method returning the Module_WallNotes property value.
        /// </summary>
        /// <returns>The Module_WallNotes property value.</returns>
        public static string Module_WallNotesFormat() {
            return Module_WallNotes;
        }
        
        /// <summary>
        /// The stub formatting method returning the MyWall_Title property value.
        /// </summary>
        /// <returns>The MyWall_Title property value.</returns>
        public static string MyWall_TitleFormat() {
            return MyWall_Title;
        }
        
        /// <summary>
        /// The stub formatting method returning the News_ReadMore_Title property value.
        /// </summary>
        /// <returns>The News_ReadMore_Title property value.</returns>
        public static string News_ReadMore_TitleFormat() {
            return News_ReadMore_Title;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageFooter_About property value.
        /// </summary>
        /// <returns>The PageFooter_About property value.</returns>
        public static string PageFooter_AboutFormat() {
            return PageFooter_About;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageFooter_AdditionalResources property value.
        /// </summary>
        /// <returns>The PageFooter_AdditionalResources property value.</returns>
        public static string PageFooter_AdditionalResourcesFormat() {
            return PageFooter_AdditionalResources;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageFooter_ConnectWithUs property value.
        /// </summary>
        /// <returns>The PageFooter_ConnectWithUs property value.</returns>
        public static string PageFooter_ConnectWithUsFormat() {
            return PageFooter_ConnectWithUs;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageFooter_Copyright property value.
        /// </summary>
        /// <returns>The PageFooter_Copyright property value.</returns>
        public static string PageFooter_CopyrightFormat() {
            return PageFooter_Copyright;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageFooter_FacebookFan property value.
        /// </summary>
        /// <returns>The PageFooter_FacebookFan property value.</returns>
        public static string PageFooter_FacebookFanFormat() {
            return PageFooter_FacebookFan;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageFooter_GeneralInfo property value.
        /// </summary>
        /// <returns>The PageFooter_GeneralInfo property value.</returns>
        public static string PageFooter_GeneralInfoFormat() {
            return PageFooter_GeneralInfo;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageFooter_Home property value.
        /// </summary>
        /// <returns>The PageFooter_Home property value.</returns>
        public static string PageFooter_HomeFormat() {
            return PageFooter_Home;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageFooter_Licensing property value.
        /// </summary>
        /// <returns>The PageFooter_Licensing property value.</returns>
        public static string PageFooter_LicensingFormat() {
            return PageFooter_Licensing;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageFooter_LinkedInConnect property value.
        /// </summary>
        /// <returns>The PageFooter_LinkedInConnect property value.</returns>
        public static string PageFooter_LinkedInConnectFormat() {
            return PageFooter_LinkedInConnect;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageFooter_PrivacyPolicy property value.
        /// </summary>
        /// <returns>The PageFooter_PrivacyPolicy property value.</returns>
        public static string PageFooter_PrivacyPolicyFormat() {
            return PageFooter_PrivacyPolicy;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageFooter_SiteMembership property value.
        /// </summary>
        /// <returns>The PageFooter_SiteMembership property value.</returns>
        public static string PageFooter_SiteMembershipFormat() {
            return PageFooter_SiteMembership;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageFooter_SocialNetworking property value.
        /// </summary>
        /// <returns>The PageFooter_SocialNetworking property value.</returns>
        public static string PageFooter_SocialNetworkingFormat() {
            return PageFooter_SocialNetworking;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageFooter_SocialNetworkingBlog property value.
        /// </summary>
        /// <returns>The PageFooter_SocialNetworkingBlog property value.</returns>
        public static string PageFooter_SocialNetworkingBlogFormat() {
            return PageFooter_SocialNetworkingBlog;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageFooter_SocialNetworkingGroups property value.
        /// </summary>
        /// <returns>The PageFooter_SocialNetworkingGroups property value.</returns>
        public static string PageFooter_SocialNetworkingGroupsFormat() {
            return PageFooter_SocialNetworkingGroups;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageFooter_SocialNetworkingHome property value.
        /// </summary>
        /// <returns>The PageFooter_SocialNetworkingHome property value.</returns>
        public static string PageFooter_SocialNetworkingHomeFormat() {
            return PageFooter_SocialNetworkingHome;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageFooter_SocialNetworkingPhotos property value.
        /// </summary>
        /// <returns>The PageFooter_SocialNetworkingPhotos property value.</returns>
        public static string PageFooter_SocialNetworkingPhotosFormat() {
            return PageFooter_SocialNetworkingPhotos;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageFooter_TermsOfUse property value.
        /// </summary>
        /// <returns>The PageFooter_TermsOfUse property value.</returns>
        public static string PageFooter_TermsOfUseFormat() {
            return PageFooter_TermsOfUse;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageFooter_TwitterFollow property value.
        /// </summary>
        /// <returns>The PageFooter_TwitterFollow property value.</returns>
        public static string PageFooter_TwitterFollowFormat() {
            return PageFooter_TwitterFollow;
        }
        
        /// <summary>
        /// The stub formatting method returning the PhotoGallery_Title property value.
        /// </summary>
        /// <returns>The PhotoGallery_Title property value.</returns>
        public static string PhotoGallery_TitleFormat() {
            return PhotoGallery_Title;
        }
        
        /// <summary>
        /// The stub formatting method returning the Title_AdditionalResources property value.
        /// </summary>
        /// <returns>The Title_AdditionalResources property value.</returns>
        public static string Title_AdditionalResourcesFormat() {
            return Title_AdditionalResources;
        }
        
        /// <summary>
        /// The stub formatting method returning the Title_BottomSection property value.
        /// </summary>
        /// <returns>The Title_BottomSection property value.</returns>
        public static string Title_BottomSectionFormat() {
            return Title_BottomSection;
        }
        
        /// <summary>
        /// The stub formatting method returning the Title_DescriptionOfFeatures property value.
        /// </summary>
        /// <returns>The Title_DescriptionOfFeatures property value.</returns>
        public static string Title_DescriptionOfFeaturesFormat() {
            return Title_DescriptionOfFeatures;
        }
        
        /// <summary>
        /// The stub formatting method returning the Title_FeaturedProjects property value.
        /// </summary>
        /// <returns>The Title_FeaturedProjects property value.</returns>
        public static string Title_FeaturedProjectsFormat() {
            return Title_FeaturedProjects;
        }
        
        /// <summary>
        /// The stub formatting method returning the Title_LeftSection property value.
        /// </summary>
        /// <returns>The Title_LeftSection property value.</returns>
        public static string Title_LeftSectionFormat() {
            return Title_LeftSection;
        }
        
        /// <summary>
        /// The stub formatting method returning the Title_MiddleSection property value.
        /// </summary>
        /// <returns>The Title_MiddleSection property value.</returns>
        public static string Title_MiddleSectionFormat() {
            return Title_MiddleSection;
        }
        
        /// <summary>
        /// The stub formatting method returning the Title_Resources property value.
        /// </summary>
        /// <returns>The Title_Resources property value.</returns>
        public static string Title_ResourcesFormat() {
            return Title_Resources;
        }
        
        /// <summary>
        /// The stub formatting method returning the Title_RightSection property value.
        /// </summary>
        /// <returns>The Title_RightSection property value.</returns>
        public static string Title_RightSectionFormat() {
            return Title_RightSection;
        }
        
        /// <summary>
        /// The stub formatting method returning the Title_ScreenGallery property value.
        /// </summary>
        /// <returns>The Title_ScreenGallery property value.</returns>
        public static string Title_ScreenGalleryFormat() {
            return Title_ScreenGallery;
        }
        
        /// <summary>
        /// The stub formatting method returning the Title_SearchResults property value.
        /// </summary>
        /// <returns>The Title_SearchResults property value.</returns>
        public static string Title_SearchResultsFormat() {
            return Title_SearchResults;
        }
        
        /// <summary>
        /// The stub formatting method returning the Title_TopSection property value.
        /// </summary>
        /// <returns>The Title_TopSection property value.</returns>
        public static string Title_TopSectionFormat() {
            return Title_TopSection;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfile_DiscussionMessages_Title property value.
        /// </summary>
        /// <returns>The UserProfile_DiscussionMessages_Title property value.</returns>
        public static string UserProfile_DiscussionMessages_TitleFormat() {
            return UserProfile_DiscussionMessages_Title;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfile_FriendSuggestion_Title property value.
        /// </summary>
        /// <returns>The UserProfile_FriendSuggestion_Title property value.</returns>
        public static string UserProfile_FriendSuggestion_TitleFormat() {
            return UserProfile_FriendSuggestion_Title;
        }
        
        /// <summary>
        /// Formats a localized string similar to '{0}&apos;s Location'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string UserProfile_Map_TitleFormat(object arg0) {
            return string.Format(_resourceCulture, UserProfile_Map_Title, arg0);
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfile_NoSuchUser property value.
        /// </summary>
        /// <returns>The UserProfile_NoSuchUser property value.</returns>
        public static string UserProfile_NoSuchUserFormat() {
            return UserProfile_NoSuchUser;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfile_PeopleSearch_InfoText property value.
        /// </summary>
        /// <returns>The UserProfile_PeopleSearch_InfoText property value.</returns>
        public static string UserProfile_PeopleSearch_InfoTextFormat() {
            return UserProfile_PeopleSearch_InfoText;
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Invite {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string UserProfile_PeopleSearch_TitleFormat(object arg0) {
            return string.Format(_resourceCulture, UserProfile_PeopleSearch_Title, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'User profile for {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string UserProfile_TitleFormat(object arg0) {
            return string.Format(_resourceCulture, UserProfile_Title, arg0);
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfile_UserProfile_Title property value.
        /// </summary>
        /// <returns>The UserProfile_UserProfile_Title property value.</returns>
        public static string UserProfile_UserProfile_TitleFormat() {
            return UserProfile_UserProfile_Title;
        }
        
        /// <summary>
        /// The stub formatting method returning the Wall_Title property value.
        /// </summary>
        /// <returns>The Wall_Title property value.</returns>
        public static string Wall_TitleFormat() {
            return Wall_Title;
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Wall notes for {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string Wall_WallNotes_TitleFormat(object arg0) {
            return string.Format(_resourceCulture, Wall_WallNotes_Title, arg0);
        }
        
        /// <summary>
        /// The stub formatting method returning the Zone_BottomPartZone property value.
        /// </summary>
        /// <returns>The Zone_BottomPartZone property value.</returns>
        public static string Zone_BottomPartZoneFormat() {
            return Zone_BottomPartZone;
        }
        
        /// <summary>
        /// The stub formatting method returning the Zone_ContentZone property value.
        /// </summary>
        /// <returns>The Zone_ContentZone property value.</returns>
        public static string Zone_ContentZoneFormat() {
            return Zone_ContentZone;
        }
        
        /// <summary>
        /// The stub formatting method returning the Zone_FeaturedProjectsZone property value.
        /// </summary>
        /// <returns>The Zone_FeaturedProjectsZone property value.</returns>
        public static string Zone_FeaturedProjectsZoneFormat() {
            return Zone_FeaturedProjectsZone;
        }
        
        /// <summary>
        /// The stub formatting method returning the Zone_LeftPartZone property value.
        /// </summary>
        /// <returns>The Zone_LeftPartZone property value.</returns>
        public static string Zone_LeftPartZoneFormat() {
            return Zone_LeftPartZone;
        }
        
        /// <summary>
        /// The stub formatting method returning the Zone_MiddlePartZone property value.
        /// </summary>
        /// <returns>The Zone_MiddlePartZone property value.</returns>
        public static string Zone_MiddlePartZoneFormat() {
            return Zone_MiddlePartZone;
        }
        
        /// <summary>
        /// The stub formatting method returning the Zone_RightPartZone property value.
        /// </summary>
        /// <returns>The Zone_RightPartZone property value.</returns>
        public static string Zone_RightPartZoneFormat() {
            return Zone_RightPartZone;
        }
        
        /// <summary>
        /// The stub formatting method returning the Zone_SocialZone property value.
        /// </summary>
        /// <returns>The Zone_SocialZone property value.</returns>
        public static string Zone_SocialZoneFormat() {
            return Zone_SocialZone;
        }
        
        /// <summary>
        /// The stub formatting method returning the Zone_TopPartZone property value.
        /// </summary>
        /// <returns>The Zone_TopPartZone property value.</returns>
        public static string Zone_TopPartZoneFormat() {
            return Zone_TopPartZone;
        }
    }
}
