//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoSoftware.MonoX.Resources {
    using System;
    using System.Web.Configuration;
    using MonoSoftware.Web.ResourceProviderModel;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorProviderModel custom tool. (Mono Wrapper based on Dmytro Kryvko builder)
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorProviderModel custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2014 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MonoSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "4.8.40.4594")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class UserProfileResources {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserProfileResources() {
        }
        
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            System.Threading.Interlocked.Exchange(ref _resourceManager, MonoSoftware.Web.ResourceProviderModel.ResourceManagerProvider.GetResourceManager("MonoSoftware.MonoX.MonoX.Resources.UserProfileResources", typeof(UserProfileResources).Assembly));
                        }
                    }
                    finally {
                        System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_AboutMySelf'.
        /// </summary>
        public static string EditProfile_AboutMySelf_PropertyName {
            get {
                return "EditProfile_AboutMySelf";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'About me:'.
        /// </summary>
        public static string EditProfile_AboutMySelf {
            get {
                return ResourceManager.GetString("EditProfile_AboutMySelf", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_Address'.
        /// </summary>
        public static string EditProfile_Address_PropertyName {
            get {
                return "EditProfile_Address";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Address:'.
        /// </summary>
        public static string EditProfile_Address {
            get {
                return ResourceManager.GetString("EditProfile_Address", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_BirthDate'.
        /// </summary>
        public static string EditProfile_BirthDate_PropertyName {
            get {
                return "EditProfile_BirthDate";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Date of birth:'.
        /// </summary>
        public static string EditProfile_BirthDate {
            get {
                return ResourceManager.GetString("EditProfile_BirthDate", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_City'.
        /// </summary>
        public static string EditProfile_City_PropertyName {
            get {
                return "EditProfile_City";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'City:'.
        /// </summary>
        public static string EditProfile_City {
            get {
                return ResourceManager.GetString("EditProfile_City", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_ConfirmPassword'.
        /// </summary>
        public static string EditProfile_ConfirmPassword_PropertyName {
            get {
                return "EditProfile_ConfirmPassword";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Confirm password:'.
        /// </summary>
        public static string EditProfile_ConfirmPassword {
            get {
                return ResourceManager.GetString("EditProfile_ConfirmPassword", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_Country'.
        /// </summary>
        public static string EditProfile_Country_PropertyName {
            get {
                return "EditProfile_Country";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Country:'.
        /// </summary>
        public static string EditProfile_Country {
            get {
                return ResourceManager.GetString("EditProfile_Country", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_Email'.
        /// </summary>
        public static string EditProfile_Email_PropertyName {
            get {
                return "EditProfile_Email";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'E-mail:'.
        /// </summary>
        public static string EditProfile_Email {
            get {
                return ResourceManager.GetString("EditProfile_Email", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_FirstName'.
        /// </summary>
        public static string EditProfile_FirstName_PropertyName {
            get {
                return "EditProfile_FirstName";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'First name:'.
        /// </summary>
        public static string EditProfile_FirstName {
            get {
                return ResourceManager.GetString("EditProfile_FirstName", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_Info'.
        /// </summary>
        public static string EditProfile_Info_PropertyName {
            get {
                return "EditProfile_Info";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Please use this form to change your profile.'.
        /// </summary>
        public static string EditProfile_Info {
            get {
                return ResourceManager.GetString("EditProfile_Info", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_LastName'.
        /// </summary>
        public static string EditProfile_LastName_PropertyName {
            get {
                return "EditProfile_LastName";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Last name:'.
        /// </summary>
        public static string EditProfile_LastName {
            get {
                return ResourceManager.GetString("EditProfile_LastName", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_NoUser'.
        /// </summary>
        public static string EditProfile_NoUser_PropertyName {
            get {
                return "EditProfile_NoUser";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'User does not exist.'.
        /// </summary>
        public static string EditProfile_NoUser {
            get {
                return ResourceManager.GetString("EditProfile_NoUser", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_Password'.
        /// </summary>
        public static string EditProfile_Password_PropertyName {
            get {
                return "EditProfile_Password";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Password:'.
        /// </summary>
        public static string EditProfile_Password {
            get {
                return ResourceManager.GetString("EditProfile_Password", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_PasswordCompareErrorMessage'.
        /// </summary>
        public static string EditProfile_PasswordCompareErrorMessage_PropertyName {
            get {
                return "EditProfile_PasswordCompareErrorMessage";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Passwords don&apos;t match.'.
        /// </summary>
        public static string EditProfile_PasswordCompareErrorMessage {
            get {
                return ResourceManager.GetString("EditProfile_PasswordCompareErrorMessage", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_PasswordCompareText'.
        /// </summary>
        public static string EditProfile_PasswordCompareText_PropertyName {
            get {
                return "EditProfile_PasswordCompareText";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '!'.
        /// </summary>
        public static string EditProfile_PasswordCompareText {
            get {
                return ResourceManager.GetString("EditProfile_PasswordCompareText", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_PasswordLengthErrorMessageFormat'.
        /// </summary>
        public static string EditProfile_PasswordLengthErrorMessageFormat_PropertyName {
            get {
                return "EditProfile_PasswordLengthErrorMessageFormat";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The length of parameter &quot;Password&quot; needs to be greater or equal to &apos;{0}&apos;'.
        /// </summary>
        public static string EditProfile_PasswordLengthErrorMessageFormat {
            get {
                return ResourceManager.GetString("EditProfile_PasswordLengthErrorMessageFormat", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_PasswordLengthText'.
        /// </summary>
        public static string EditProfile_PasswordLengthText_PropertyName {
            get {
                return "EditProfile_PasswordLengthText";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '!'.
        /// </summary>
        public static string EditProfile_PasswordLengthText {
            get {
                return ResourceManager.GetString("EditProfile_PasswordLengthText", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_RegexEmailErrorMessage'.
        /// </summary>
        public static string EditProfile_RegexEmailErrorMessage_PropertyName {
            get {
                return "EditProfile_RegexEmailErrorMessage";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'E-Mail is invalid.'.
        /// </summary>
        public static string EditProfile_RegexEmailErrorMessage {
            get {
                return ResourceManager.GetString("EditProfile_RegexEmailErrorMessage", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_RegexEmailText'.
        /// </summary>
        public static string EditProfile_RegexEmailText_PropertyName {
            get {
                return "EditProfile_RegexEmailText";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '!'.
        /// </summary>
        public static string EditProfile_RegexEmailText {
            get {
                return ResourceManager.GetString("EditProfile_RegexEmailText", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_ReqFirstNameErrorMessage'.
        /// </summary>
        public static string EditProfile_ReqFirstNameErrorMessage_PropertyName {
            get {
                return "EditProfile_ReqFirstNameErrorMessage";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'First name is required.'.
        /// </summary>
        public static string EditProfile_ReqFirstNameErrorMessage {
            get {
                return ResourceManager.GetString("EditProfile_ReqFirstNameErrorMessage", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_ReqFirstNameText'.
        /// </summary>
        public static string EditProfile_ReqFirstNameText_PropertyName {
            get {
                return "EditProfile_ReqFirstNameText";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '*'.
        /// </summary>
        public static string EditProfile_ReqFirstNameText {
            get {
                return ResourceManager.GetString("EditProfile_ReqFirstNameText", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_ReqLastNameErrorMessage'.
        /// </summary>
        public static string EditProfile_ReqLastNameErrorMessage_PropertyName {
            get {
                return "EditProfile_ReqLastNameErrorMessage";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Last name is required.'.
        /// </summary>
        public static string EditProfile_ReqLastNameErrorMessage {
            get {
                return ResourceManager.GetString("EditProfile_ReqLastNameErrorMessage", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_ReqLastNameText'.
        /// </summary>
        public static string EditProfile_ReqLastNameText_PropertyName {
            get {
                return "EditProfile_ReqLastNameText";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '*'.
        /// </summary>
        public static string EditProfile_ReqLastNameText {
            get {
                return ResourceManager.GetString("EditProfile_ReqLastNameText", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_RowBasicInfo'.
        /// </summary>
        public static string EditProfile_RowBasicInfo_PropertyName {
            get {
                return "EditProfile_RowBasicInfo";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'BASIC INFORMATION'.
        /// </summary>
        public static string EditProfile_RowBasicInfo {
            get {
                return ResourceManager.GetString("EditProfile_RowBasicInfo", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_RowOtherInfo'.
        /// </summary>
        public static string EditProfile_RowOtherInfo_PropertyName {
            get {
                return "EditProfile_RowOtherInfo";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'OTHER INFORMATION'.
        /// </summary>
        public static string EditProfile_RowOtherInfo {
            get {
                return ResourceManager.GetString("EditProfile_RowOtherInfo", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_RowPasswordTitle'.
        /// </summary>
        public static string EditProfile_RowPasswordTitle_PropertyName {
            get {
                return "EditProfile_RowPasswordTitle";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Please enter your password twice due to security reasons. Your password should contain at least 6 characters or numbers.'.
        /// </summary>
        public static string EditProfile_RowPasswordTitle {
            get {
                return ResourceManager.GetString("EditProfile_RowPasswordTitle", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_Saved'.
        /// </summary>
        public static string EditProfile_Saved_PropertyName {
            get {
                return "EditProfile_Saved";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Profile has been successfully saved.'.
        /// </summary>
        public static string EditProfile_Saved {
            get {
                return ResourceManager.GetString("EditProfile_Saved", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_TimeZone'.
        /// </summary>
        public static string EditProfile_TimeZone_PropertyName {
            get {
                return "EditProfile_TimeZone";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Time zone'.
        /// </summary>
        public static string EditProfile_TimeZone {
            get {
                return ResourceManager.GetString("EditProfile_TimeZone", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_Title'.
        /// </summary>
        public static string EditProfile_Title_PropertyName {
            get {
                return "EditProfile_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Configure your profile'.
        /// </summary>
        public static string EditProfile_Title {
            get {
                return ResourceManager.GetString("EditProfile_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_Validation_Url'.
        /// </summary>
        public static string EditProfile_Validation_Url_PropertyName {
            get {
                return "EditProfile_Validation_Url";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Please enter a correct Web site address, starting with http:// prefix.'.
        /// </summary>
        public static string EditProfile_Validation_Url {
            get {
                return ResourceManager.GetString("EditProfile_Validation_Url", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_ValSumHeaderText'.
        /// </summary>
        public static string EditProfile_ValSumHeaderText_PropertyName {
            get {
                return "EditProfile_ValSumHeaderText";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Please correct the following:'.
        /// </summary>
        public static string EditProfile_ValSumHeaderText {
            get {
                return ResourceManager.GetString("EditProfile_ValSumHeaderText", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_WebSites'.
        /// </summary>
        public static string EditProfile_WebSites_PropertyName {
            get {
                return "EditProfile_WebSites";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'My web sites:'.
        /// </summary>
        public static string EditProfile_WebSites {
            get {
                return ResourceManager.GetString("EditProfile_WebSites", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'EditProfile_ZipCode'.
        /// </summary>
        public static string EditProfile_ZipCode_PropertyName {
            get {
                return "EditProfile_ZipCode";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Zip code:'.
        /// </summary>
        public static string EditProfile_ZipCode {
            get {
                return ResourceManager.GetString("EditProfile_ZipCode", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserAvatar_Caption'.
        /// </summary>
        public static string UserAvatar_Caption_PropertyName {
            get {
                return "UserAvatar_Caption";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'User avatar'.
        /// </summary>
        public static string UserAvatar_Caption {
            get {
                return ResourceManager.GetString("UserAvatar_Caption", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserAvatar_InvalidFile'.
        /// </summary>
        public static string UserAvatar_InvalidFile_PropertyName {
            get {
                return "UserAvatar_InvalidFile";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Invalid file.'.
        /// </summary>
        public static string UserAvatar_InvalidFile {
            get {
                return ResourceManager.GetString("UserAvatar_InvalidFile", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserAvatart_InvalidImageSize'.
        /// </summary>
        public static string UserAvatart_InvalidImageSize_PropertyName {
            get {
                return "UserAvatart_InvalidImageSize";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Desired image dimensions you have uploaded are too small.'.
        /// </summary>
        public static string UserAvatart_InvalidImageSize {
            get {
                return ResourceManager.GetString("UserAvatart_InvalidImageSize", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfile_Browse'.
        /// </summary>
        public static string UserProfile_Browse_PropertyName {
            get {
                return "UserProfile_Browse";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Browse'.
        /// </summary>
        public static string UserProfile_Browse {
            get {
                return ResourceManager.GetString("UserProfile_Browse", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfile_Clear'.
        /// </summary>
        public static string UserProfile_Clear_PropertyName {
            get {
                return "UserProfile_Clear";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Clear the avatar'.
        /// </summary>
        public static string UserProfile_Clear {
            get {
                return ResourceManager.GetString("UserProfile_Clear", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfile_Save'.
        /// </summary>
        public static string UserProfile_Save_PropertyName {
            get {
                return "UserProfile_Save";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Save'.
        /// </summary>
        public static string UserProfile_Save {
            get {
                return ResourceManager.GetString("UserProfile_Save", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfileHeader_About'.
        /// </summary>
        public static string UserProfileHeader_About_PropertyName {
            get {
                return "UserProfileHeader_About";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'About'.
        /// </summary>
        public static string UserProfileHeader_About {
            get {
                return ResourceManager.GetString("UserProfileHeader_About", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfileHeader_Friends'.
        /// </summary>
        public static string UserProfileHeader_Friends_PropertyName {
            get {
                return "UserProfileHeader_Friends";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Friends'.
        /// </summary>
        public static string UserProfileHeader_Friends {
            get {
                return ResourceManager.GetString("UserProfileHeader_Friends", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfileHeader_MyWall'.
        /// </summary>
        public static string UserProfileHeader_MyWall_PropertyName {
            get {
                return "UserProfileHeader_MyWall";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Wall'.
        /// </summary>
        public static string UserProfileHeader_MyWall {
            get {
                return ResourceManager.GetString("UserProfileHeader_MyWall", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfileHeader_Photos'.
        /// </summary>
        public static string UserProfileHeader_Photos_PropertyName {
            get {
                return "UserProfileHeader_Photos";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Photos'.
        /// </summary>
        public static string UserProfileHeader_Photos {
            get {
                return ResourceManager.GetString("UserProfileHeader_Photos", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfileModule_CompleteProfile'.
        /// </summary>
        public static string UserProfileModule_CompleteProfile_PropertyName {
            get {
                return "UserProfileModule_CompleteProfile";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Complete your profile by clicking on the edit link.'.
        /// </summary>
        public static string UserProfileModule_CompleteProfile {
            get {
                return ResourceManager.GetString("UserProfileModule_CompleteProfile", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfileModule_DefaultMyStatusText'.
        /// </summary>
        public static string UserProfileModule_DefaultMyStatusText_PropertyName {
            get {
                return "UserProfileModule_DefaultMyStatusText";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Type your status here ...'.
        /// </summary>
        public static string UserProfileModule_DefaultMyStatusText {
            get {
                return ResourceManager.GetString("UserProfileModule_DefaultMyStatusText", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfileModule_EditProfile'.
        /// </summary>
        public static string UserProfileModule_EditProfile_PropertyName {
            get {
                return "UserProfileModule_EditProfile";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Edit'.
        /// </summary>
        public static string UserProfileModule_EditProfile {
            get {
                return ResourceManager.GetString("UserProfileModule_EditProfile", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfileModule_MyStatusEmpty'.
        /// </summary>
        public static string UserProfileModule_MyStatusEmpty_PropertyName {
            get {
                return "UserProfileModule_MyStatusEmpty";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Your status goes here'.
        /// </summary>
        public static string UserProfileModule_MyStatusEmpty {
            get {
                return ResourceManager.GetString("UserProfileModule_MyStatusEmpty", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfileModule_RemoveStatus_ToolTip'.
        /// </summary>
        public static string UserProfileModule_RemoveStatus_ToolTip_PropertyName {
            get {
                return "UserProfileModule_RemoveStatus_ToolTip";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Remove / Clear my status'.
        /// </summary>
        public static string UserProfileModule_RemoveStatus_ToolTip {
            get {
                return ResourceManager.GetString("UserProfileModule_RemoveStatus_ToolTip", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfileModule_SetMyStatus'.
        /// </summary>
        public static string UserProfileModule_SetMyStatus_PropertyName {
            get {
                return "UserProfileModule_SetMyStatus";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Submit'.
        /// </summary>
        public static string UserProfileModule_SetMyStatus {
            get {
                return ResourceManager.GetString("UserProfileModule_SetMyStatus", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfileModule_Title'.
        /// </summary>
        public static string UserProfileModule_Title_PropertyName {
            get {
                return "UserProfileModule_Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'User profile'.
        /// </summary>
        public static string UserProfileModule_Title {
            get {
                return ResourceManager.GetString("UserProfileModule_Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfileModule_User'.
        /// </summary>
        public static string UserProfileModule_User_PropertyName {
            get {
                return "UserProfileModule_User";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Choose a user:'.
        /// </summary>
        public static string UserProfileModule_User {
            get {
                return ResourceManager.GetString("UserProfileModule_User", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserProfileModule_ViewProfile'.
        /// </summary>
        public static string UserProfileModule_ViewProfile_PropertyName {
            get {
                return "UserProfileModule_ViewProfile";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'View'.
        /// </summary>
        public static string UserProfileModule_ViewProfile {
            get {
                return ResourceManager.GetString("UserProfileModule_ViewProfile", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'UserScore'.
        /// </summary>
        public static string UserScore_PropertyName {
            get {
                return "UserScore";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Reputation'.
        /// </summary>
        public static string UserScore {
            get {
                return ResourceManager.GetString("UserScore", _resourceCulture);
            }
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_AboutMySelf property value.
        /// </summary>
        /// <returns>The EditProfile_AboutMySelf property value.</returns>
        public static string EditProfile_AboutMySelfFormat() {
            return EditProfile_AboutMySelf;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_Address property value.
        /// </summary>
        /// <returns>The EditProfile_Address property value.</returns>
        public static string EditProfile_AddressFormat() {
            return EditProfile_Address;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_BirthDate property value.
        /// </summary>
        /// <returns>The EditProfile_BirthDate property value.</returns>
        public static string EditProfile_BirthDateFormat() {
            return EditProfile_BirthDate;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_City property value.
        /// </summary>
        /// <returns>The EditProfile_City property value.</returns>
        public static string EditProfile_CityFormat() {
            return EditProfile_City;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_ConfirmPassword property value.
        /// </summary>
        /// <returns>The EditProfile_ConfirmPassword property value.</returns>
        public static string EditProfile_ConfirmPasswordFormat() {
            return EditProfile_ConfirmPassword;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_Country property value.
        /// </summary>
        /// <returns>The EditProfile_Country property value.</returns>
        public static string EditProfile_CountryFormat() {
            return EditProfile_Country;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_Email property value.
        /// </summary>
        /// <returns>The EditProfile_Email property value.</returns>
        public static string EditProfile_EmailFormat() {
            return EditProfile_Email;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_FirstName property value.
        /// </summary>
        /// <returns>The EditProfile_FirstName property value.</returns>
        public static string EditProfile_FirstNameFormat() {
            return EditProfile_FirstName;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_Info property value.
        /// </summary>
        /// <returns>The EditProfile_Info property value.</returns>
        public static string EditProfile_InfoFormat() {
            return EditProfile_Info;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_LastName property value.
        /// </summary>
        /// <returns>The EditProfile_LastName property value.</returns>
        public static string EditProfile_LastNameFormat() {
            return EditProfile_LastName;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_NoUser property value.
        /// </summary>
        /// <returns>The EditProfile_NoUser property value.</returns>
        public static string EditProfile_NoUserFormat() {
            return EditProfile_NoUser;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_Password property value.
        /// </summary>
        /// <returns>The EditProfile_Password property value.</returns>
        public static string EditProfile_PasswordFormat() {
            return EditProfile_Password;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_PasswordCompareErrorMessage property value.
        /// </summary>
        /// <returns>The EditProfile_PasswordCompareErrorMessage property value.</returns>
        public static string EditProfile_PasswordCompareErrorMessageFormat() {
            return EditProfile_PasswordCompareErrorMessage;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_PasswordCompareText property value.
        /// </summary>
        /// <returns>The EditProfile_PasswordCompareText property value.</returns>
        public static string EditProfile_PasswordCompareTextFormat() {
            return EditProfile_PasswordCompareText;
        }
        
        /// <summary>
        /// Formats a localized string similar to 'The length of parameter &quot;Password&quot; needs to be greater or equal to &apos;{0}&apos;'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string EditProfile_PasswordLengthErrorMessageFormatFormat(object arg0) {
            return string.Format(_resourceCulture, EditProfile_PasswordLengthErrorMessageFormat, arg0);
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_PasswordLengthText property value.
        /// </summary>
        /// <returns>The EditProfile_PasswordLengthText property value.</returns>
        public static string EditProfile_PasswordLengthTextFormat() {
            return EditProfile_PasswordLengthText;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_RegexEmailErrorMessage property value.
        /// </summary>
        /// <returns>The EditProfile_RegexEmailErrorMessage property value.</returns>
        public static string EditProfile_RegexEmailErrorMessageFormat() {
            return EditProfile_RegexEmailErrorMessage;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_RegexEmailText property value.
        /// </summary>
        /// <returns>The EditProfile_RegexEmailText property value.</returns>
        public static string EditProfile_RegexEmailTextFormat() {
            return EditProfile_RegexEmailText;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_ReqFirstNameErrorMessage property value.
        /// </summary>
        /// <returns>The EditProfile_ReqFirstNameErrorMessage property value.</returns>
        public static string EditProfile_ReqFirstNameErrorMessageFormat() {
            return EditProfile_ReqFirstNameErrorMessage;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_ReqFirstNameText property value.
        /// </summary>
        /// <returns>The EditProfile_ReqFirstNameText property value.</returns>
        public static string EditProfile_ReqFirstNameTextFormat() {
            return EditProfile_ReqFirstNameText;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_ReqLastNameErrorMessage property value.
        /// </summary>
        /// <returns>The EditProfile_ReqLastNameErrorMessage property value.</returns>
        public static string EditProfile_ReqLastNameErrorMessageFormat() {
            return EditProfile_ReqLastNameErrorMessage;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_ReqLastNameText property value.
        /// </summary>
        /// <returns>The EditProfile_ReqLastNameText property value.</returns>
        public static string EditProfile_ReqLastNameTextFormat() {
            return EditProfile_ReqLastNameText;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_RowBasicInfo property value.
        /// </summary>
        /// <returns>The EditProfile_RowBasicInfo property value.</returns>
        public static string EditProfile_RowBasicInfoFormat() {
            return EditProfile_RowBasicInfo;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_RowOtherInfo property value.
        /// </summary>
        /// <returns>The EditProfile_RowOtherInfo property value.</returns>
        public static string EditProfile_RowOtherInfoFormat() {
            return EditProfile_RowOtherInfo;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_RowPasswordTitle property value.
        /// </summary>
        /// <returns>The EditProfile_RowPasswordTitle property value.</returns>
        public static string EditProfile_RowPasswordTitleFormat() {
            return EditProfile_RowPasswordTitle;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_Saved property value.
        /// </summary>
        /// <returns>The EditProfile_Saved property value.</returns>
        public static string EditProfile_SavedFormat() {
            return EditProfile_Saved;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_TimeZone property value.
        /// </summary>
        /// <returns>The EditProfile_TimeZone property value.</returns>
        public static string EditProfile_TimeZoneFormat() {
            return EditProfile_TimeZone;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_Title property value.
        /// </summary>
        /// <returns>The EditProfile_Title property value.</returns>
        public static string EditProfile_TitleFormat() {
            return EditProfile_Title;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_Validation_Url property value.
        /// </summary>
        /// <returns>The EditProfile_Validation_Url property value.</returns>
        public static string EditProfile_Validation_UrlFormat() {
            return EditProfile_Validation_Url;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_ValSumHeaderText property value.
        /// </summary>
        /// <returns>The EditProfile_ValSumHeaderText property value.</returns>
        public static string EditProfile_ValSumHeaderTextFormat() {
            return EditProfile_ValSumHeaderText;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_WebSites property value.
        /// </summary>
        /// <returns>The EditProfile_WebSites property value.</returns>
        public static string EditProfile_WebSitesFormat() {
            return EditProfile_WebSites;
        }
        
        /// <summary>
        /// The stub formatting method returning the EditProfile_ZipCode property value.
        /// </summary>
        /// <returns>The EditProfile_ZipCode property value.</returns>
        public static string EditProfile_ZipCodeFormat() {
            return EditProfile_ZipCode;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserAvatar_Caption property value.
        /// </summary>
        /// <returns>The UserAvatar_Caption property value.</returns>
        public static string UserAvatar_CaptionFormat() {
            return UserAvatar_Caption;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserAvatar_InvalidFile property value.
        /// </summary>
        /// <returns>The UserAvatar_InvalidFile property value.</returns>
        public static string UserAvatar_InvalidFileFormat() {
            return UserAvatar_InvalidFile;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserAvatart_InvalidImageSize property value.
        /// </summary>
        /// <returns>The UserAvatart_InvalidImageSize property value.</returns>
        public static string UserAvatart_InvalidImageSizeFormat() {
            return UserAvatart_InvalidImageSize;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfile_Browse property value.
        /// </summary>
        /// <returns>The UserProfile_Browse property value.</returns>
        public static string UserProfile_BrowseFormat() {
            return UserProfile_Browse;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfile_Clear property value.
        /// </summary>
        /// <returns>The UserProfile_Clear property value.</returns>
        public static string UserProfile_ClearFormat() {
            return UserProfile_Clear;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfile_Save property value.
        /// </summary>
        /// <returns>The UserProfile_Save property value.</returns>
        public static string UserProfile_SaveFormat() {
            return UserProfile_Save;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfileHeader_About property value.
        /// </summary>
        /// <returns>The UserProfileHeader_About property value.</returns>
        public static string UserProfileHeader_AboutFormat() {
            return UserProfileHeader_About;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfileHeader_Friends property value.
        /// </summary>
        /// <returns>The UserProfileHeader_Friends property value.</returns>
        public static string UserProfileHeader_FriendsFormat() {
            return UserProfileHeader_Friends;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfileHeader_MyWall property value.
        /// </summary>
        /// <returns>The UserProfileHeader_MyWall property value.</returns>
        public static string UserProfileHeader_MyWallFormat() {
            return UserProfileHeader_MyWall;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfileHeader_Photos property value.
        /// </summary>
        /// <returns>The UserProfileHeader_Photos property value.</returns>
        public static string UserProfileHeader_PhotosFormat() {
            return UserProfileHeader_Photos;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfileModule_CompleteProfile property value.
        /// </summary>
        /// <returns>The UserProfileModule_CompleteProfile property value.</returns>
        public static string UserProfileModule_CompleteProfileFormat() {
            return UserProfileModule_CompleteProfile;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfileModule_DefaultMyStatusText property value.
        /// </summary>
        /// <returns>The UserProfileModule_DefaultMyStatusText property value.</returns>
        public static string UserProfileModule_DefaultMyStatusTextFormat() {
            return UserProfileModule_DefaultMyStatusText;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfileModule_EditProfile property value.
        /// </summary>
        /// <returns>The UserProfileModule_EditProfile property value.</returns>
        public static string UserProfileModule_EditProfileFormat() {
            return UserProfileModule_EditProfile;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfileModule_MyStatusEmpty property value.
        /// </summary>
        /// <returns>The UserProfileModule_MyStatusEmpty property value.</returns>
        public static string UserProfileModule_MyStatusEmptyFormat() {
            return UserProfileModule_MyStatusEmpty;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfileModule_RemoveStatus_ToolTip property value.
        /// </summary>
        /// <returns>The UserProfileModule_RemoveStatus_ToolTip property value.</returns>
        public static string UserProfileModule_RemoveStatus_ToolTipFormat() {
            return UserProfileModule_RemoveStatus_ToolTip;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfileModule_SetMyStatus property value.
        /// </summary>
        /// <returns>The UserProfileModule_SetMyStatus property value.</returns>
        public static string UserProfileModule_SetMyStatusFormat() {
            return UserProfileModule_SetMyStatus;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfileModule_Title property value.
        /// </summary>
        /// <returns>The UserProfileModule_Title property value.</returns>
        public static string UserProfileModule_TitleFormat() {
            return UserProfileModule_Title;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfileModule_User property value.
        /// </summary>
        /// <returns>The UserProfileModule_User property value.</returns>
        public static string UserProfileModule_UserFormat() {
            return UserProfileModule_User;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserProfileModule_ViewProfile property value.
        /// </summary>
        /// <returns>The UserProfileModule_ViewProfile property value.</returns>
        public static string UserProfileModule_ViewProfileFormat() {
            return UserProfileModule_ViewProfile;
        }
        
        /// <summary>
        /// The stub formatting method returning the UserScore property value.
        /// </summary>
        /// <returns>The UserScore property value.</returns>
        public static string UserScoreFormat() {
            return UserScore;
        }
    }
}
