//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoSoftware.MonoX.Resources {
    using System;
    using System.Web.Configuration;
    using MonoSoftware.Web.ResourceProviderModel;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorProviderModel custom tool. (Mono Wrapper based on Dmytro Kryvko builder)
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorProviderModel custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2013 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MonoSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "4.7.40.4282")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class CategoryContextMenuOperations {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryContextMenuOperations() {
        }
        
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            System.Threading.Interlocked.Exchange(ref _resourceManager, MonoSoftware.Web.ResourceProviderModel.ResourceManagerProvider.GetResourceManager("MonoSoftware.MonoX.MonoX.Resources.News.CategoryContextMenuOperations", typeof(CategoryContextMenuOperations).Assembly));
                        }
                    }
                    finally {
                        System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Copy'.
        /// </summary>
        public static string Copy_PropertyName {
            get {
                return "Copy";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Copy'.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Cut'.
        /// </summary>
        public static string Cut_PropertyName {
            get {
                return "Cut";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Cut'.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Delete'.
        /// </summary>
        public static string Delete_PropertyName {
            get {
                return "Delete";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Delete'.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'DeleteConfirmation'.
        /// </summary>
        public static string DeleteConfirmation_PropertyName {
            get {
                return "DeleteConfirmation";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Currently selected item will be deleted. Continue?'.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'MoveDown'.
        /// </summary>
        public static string MoveDown_PropertyName {
            get {
                return "MoveDown";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Move down'.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'MoveUp'.
        /// </summary>
        public static string MoveUp_PropertyName {
            get {
                return "MoveUp";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Move up'.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Paste'.
        /// </summary>
        public static string Paste_PropertyName {
            get {
                return "Paste";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Paste'.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PasteAfter'.
        /// </summary>
        public static string PasteAfter_PropertyName {
            get {
                return "PasteAfter";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Paste after'.
        /// </summary>
        public static string PasteAfter {
            get {
                return ResourceManager.GetString("PasteAfter", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'PasteBefore'.
        /// </summary>
        public static string PasteBefore_PropertyName {
            get {
                return "PasteBefore";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Paste before'.
        /// </summary>
        public static string PasteBefore {
            get {
                return ResourceManager.GetString("PasteBefore", _resourceCulture);
            }
        }
        
        /// <summary>
        /// The stub formatting method returning the Copy property value.
        /// </summary>
        /// <returns>The Copy property value.</returns>
        public static string CopyFormat() {
            return Copy;
        }
        
        /// <summary>
        /// The stub formatting method returning the Cut property value.
        /// </summary>
        /// <returns>The Cut property value.</returns>
        public static string CutFormat() {
            return Cut;
        }
        
        /// <summary>
        /// The stub formatting method returning the Delete property value.
        /// </summary>
        /// <returns>The Delete property value.</returns>
        public static string DeleteFormat() {
            return Delete;
        }
        
        /// <summary>
        /// The stub formatting method returning the DeleteConfirmation property value.
        /// </summary>
        /// <returns>The DeleteConfirmation property value.</returns>
        public static string DeleteConfirmationFormat() {
            return DeleteConfirmation;
        }
        
        /// <summary>
        /// The stub formatting method returning the MoveDown property value.
        /// </summary>
        /// <returns>The MoveDown property value.</returns>
        public static string MoveDownFormat() {
            return MoveDown;
        }
        
        /// <summary>
        /// The stub formatting method returning the MoveUp property value.
        /// </summary>
        /// <returns>The MoveUp property value.</returns>
        public static string MoveUpFormat() {
            return MoveUp;
        }
        
        /// <summary>
        /// The stub formatting method returning the Paste property value.
        /// </summary>
        /// <returns>The Paste property value.</returns>
        public static string PasteFormat() {
            return Paste;
        }
        
        /// <summary>
        /// The stub formatting method returning the PasteAfter property value.
        /// </summary>
        /// <returns>The PasteAfter property value.</returns>
        public static string PasteAfterFormat() {
            return PasteAfter;
        }
        
        /// <summary>
        /// The stub formatting method returning the PasteBefore property value.
        /// </summary>
        /// <returns>The PasteBefore property value.</returns>
        public static string PasteBeforeFormat() {
            return PasteBefore;
        }
    }
}
