//Project: ClipFlair (http://ClipFlair.codeplex.com)
//Filename: BaseView.cs
//Version: 20130118


using System.ComponentModel;
using System;
using System.Runtime.Serialization;
using System.Windows;
using System.Windows.Browser;

namespace ClipFlair.Windows.Views
{

  [ScriptableType]
  [DataContract(Namespace = "http://clipflair.net/Contracts/View")]
  public class BaseView: IView
  {

    public BaseView()
    {
      SetDefaults(); //ancestors don't need to call "SetDefaults" at their constructors since this constructor is always called
    }

    #region INotifyPropertyChanged

    public event PropertyChangedEventHandler PropertyChanged;

    public void RaisePropertyChanged(string PropertyName)
    {
      if (PropertyChanged != null)
        PropertyChanged(this, new PropertyChangedEventArgs(PropertyName));
    }

    #endregion

    #region Fields

    private Uri optionsSource;
    private string id;
    private string title;
    private Point position;
    private double width;
    private double height;
    private double zoom;
    private double opacity;
    private bool moveable;
    private bool resizable;
    private bool zoomable;
    private bool warnOnClosing;

    #endregion

    #region Properties

    [DataMember]
    [DefaultValue(ViewDefaults.DefaultOptionsSource)]
    public Uri OptionsSource
    {
      get { return optionsSource; }
      set
      {
        if (value != optionsSource)
        {
          optionsSource = value;
          RaisePropertyChanged(IViewProperties.PropertyOptionsSource);
        }
      }
    }

    [DataMember]
    //unique IDs are autogenerated, no default ID exists
    public string ID
    {
      get { return id; }
      set
      {
        if (value != id)
        {
          id = value;
          RaisePropertyChanged(IViewProperties.PropertyID);
        }
      }
    }    

    [DataMember]
    [DefaultValue(ViewDefaults.DefaultTitle)]
    public string Title
    {
      get { return title; }
      set
      {
        if (value != title)
        {
          title = value;
          RaisePropertyChanged(IViewProperties.PropertyTitle);
        }
      }
    }    

    [DataMember]
    //[DefaultValue(ViewDefaults.DefaultPosition)]
    public Point Position
    {
      get { return position; }
      set
      {
        if (value != position)
        {
          position = value;
          RaisePropertyChanged(IViewProperties.PropertyPosition);
        }
      }
    }

    [DataMember]
    [DefaultValue(ViewDefaults.DefaultWidth)]
    public double Width
    {
      get { return width; }
      set
      {
        if (value != width)
        {
          width = value;
          RaisePropertyChanged(IViewProperties.PropertyWidth);
        }
      }
    }

    [DataMember]
    [DefaultValue(ViewDefaults.DefaultHeight)]
    public double Height
    {
      get { return height; }
      set
      {
        if (value != height)
        {
          height = value;
          RaisePropertyChanged(IViewProperties.PropertyHeight);
        }
      }
    }

    [DataMember]
    [DefaultValue(ViewDefaults.DefaultZoom)]
    public double Zoom
    {
      get { return zoom; }
      set
      {
        if (value != zoom)
        {
          zoom = value;
          RaisePropertyChanged(IViewProperties.PropertyZoom);
        }
      }
    }

    [DataMember]
    [DefaultValue(ViewDefaults.DefaultOpacity)]
    public double Opacity
    {
      get { return opacity; }
      set
      {
        if (value != opacity)
        {
          opacity = value;
          RaisePropertyChanged(IViewProperties.PropertyOpacity);
        }
      }
    }

    [DataMember]
    [DefaultValue(ViewDefaults.DefaultMoveable)]
    public bool Moveable
    {
      get { return moveable; }
      set
      {
        if (value != moveable)
        {
          moveable = value;
          RaisePropertyChanged(IViewProperties.PropertyMoveable);
        }
      }
    }
    
    [DataMember]
    [DefaultValue(ViewDefaults.DefaultResizable)]
    public bool Resizable
    {
      get { return resizable; }
      set
      {
        if (value != resizable)
        {
          resizable = value;
          RaisePropertyChanged(IViewProperties.PropertyResizable);
        }
      }
    }

    [DataMember]
    [DefaultValue(ViewDefaults.DefaultZoomable)]
    public bool Zoomable
    {
      get { return zoomable; }
      set
      {
        if (value != zoomable)
        {
          zoomable = value;
          RaisePropertyChanged(IViewProperties.PropertyZoomable);
        }
      }
    }

    [DataMember]
    [DefaultValue(ViewDefaults.DefaultWarnOnClosing)]
    public bool WarnOnClosing
    {
      get { return warnOnClosing; }
      set
      {
        if (value != warnOnClosing)
        {
          warnOnClosing = value;
          RaisePropertyChanged(IViewProperties.PropertyWarnOnClosing);
        }
      }
    }
    
    #endregion

    #region Methods

    public virtual void SetDefaults()
    {
      ViewDefaults.SetDefaults(this); //this makes sure we set public properties (invoking "set" accessors), not fields
    }

    [OnDeserializing()] //this is called before deserialization occurs to set defaults for any properties that may be missing at the serialized data (e.g. from older serialized state)
    public void OnDeserializing(StreamingContext context) //Note that this cannot be a virtual method
    {
      SetDefaults(); //this one is a virtual method overriden by descendents (they should call "base.SetDefaults()" first there, then override any BaseView default values and then set defaults for their own properties)
    }

    #endregion

  }

}
