//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilverTextEditor.Resources
{


  /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilverTextEditor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string color_Black {
            get {
                return ResourceManager.GetString("color_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string color_Blue {
            get {
                return ResourceManager.GetString("color_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string color_Green {
            get {
                return ResourceManager.GetString("color_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string color_Red {
            get {
                return ResourceManager.GetString("color_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string color_Yellow {
            get {
                return ResourceManager.GetString("color_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string tooltip_Bold {
            get {
                return ResourceManager.GetString("tooltip_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string tooltip_Clear {
            get {
                return ResourceManager.GetString("tooltip_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Text.
        /// </summary>
        public static string tooltip_Copy {
            get {
                return ResourceManager.GetString("tooltip_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Text.
        /// </summary>
        public static string tooltip_Cut {
            get {
                return ResourceManager.GetString("tooltip_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit / View Mode.
        /// </summary>
        public static string tooltip_EditViewMode {
            get {
                return ResourceManager.GetString("tooltip_EditViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Hyperlink.
        /// </summary>
        public static string tooltip_Hyperlink {
            get {
                return ResourceManager.GetString("tooltip_Hyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image.
        /// </summary>
        public static string tooltip_Image {
            get {
                return ResourceManager.GetString("tooltip_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string tooltip_Italic {
            get {
                return ResourceManager.GetString("tooltip_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open existing document.
        /// </summary>
        public static string tooltip_Open {
            get {
                return ResourceManager.GetString("tooltip_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Text.
        /// </summary>
        public static string tooltip_Paste {
            get {
                return ResourceManager.GetString("tooltip_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Document.
        /// </summary>
        public static string tooltip_Print {
            get {
                return ResourceManager.GetString("tooltip_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to external file.
        /// </summary>
        public static string tooltip_Save {
            get {
                return ResourceManager.GetString("tooltip_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Direction.
        /// </summary>
        public static string tooltip_TextDirection {
            get {
                return ResourceManager.GetString("tooltip_TextDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert timestamp.
        /// </summary>
        public static string tooltip_Timestamp {
            get {
                return ResourceManager.GetString("tooltip_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underlined.
        /// </summary>
        public static string tooltip_Underline {
            get {
                return ResourceManager.GetString("tooltip_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string txt_Clipboard {
            get {
                return ResourceManager.GetString("txt_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string txt_Display {
            get {
                return ResourceManager.GetString("txt_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string txt_File {
            get {
                return ResourceManager.GetString("txt_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string txt_Font {
            get {
                return ResourceManager.GetString("txt_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string txt_Highlight {
            get {
                return ResourceManager.GetString("txt_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string txt_Insert {
            get {
                return ResourceManager.GetString("txt_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string txt_Print {
            get {
                return ResourceManager.GetString("txt_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string txt_Status_Ready {
            get {
                return ResourceManager.GetString("txt_Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string txt_XAML {
            get {
                return ResourceManager.GetString("txt_XAML", resourceCulture);
            }
        }
    }
}
