//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoSoftware.MonoX.Resources.WebParts {
    using System;
    using System.Web.Configuration;
    using MonoSoftware.Web.ResourceProviderModel;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorProviderModel custom tool. (Mono Wrapper based on Dmytro Kryvko builder)
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorProviderModel custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2013 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MonoSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "4.7.40.4282")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class PortalImportCatalogPart {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PortalImportCatalogPart() {
        }
        
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            System.Threading.Interlocked.Exchange(ref _resourceManager, MonoSoftware.Web.ResourceProviderModel.ResourceManagerProvider.GetResourceManager("MonoSoftware.MonoX.MonoX.Resources.WebParts.PortalImportCatalogPart", typeof(PortalImportCatalogPart).Assembly));
                        }
                    }
                    finally {
                        System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'ErrorText'.
        /// </summary>
        public static string ErrorText_PropertyName {
            get {
                return "ErrorText";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'An error has occurred while trying to upload and import selected Web part. Please make sure that all Web parts have the correct format before uploading.'.
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Title'.
        /// </summary>
        public static string Title_PropertyName {
            get {
                return "Title";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Imported parts catalog'.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Upload'.
        /// </summary>
        public static string Upload_PropertyName {
            get {
                return "Upload";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Upload'.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the strongly typed name for property 'Uploaded'.
        /// </summary>
        public static string Uploaded_PropertyName {
            get {
                return "Uploaded";
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'uploaded'.
        /// </summary>
        public static string Uploaded {
            get {
                return ResourceManager.GetString("Uploaded", _resourceCulture);
            }
        }
        
        /// <summary>
        /// The stub formatting method returning the ErrorText property value.
        /// </summary>
        /// <returns>The ErrorText property value.</returns>
        public static string ErrorTextFormat() {
            return ErrorText;
        }
        
        /// <summary>
        /// The stub formatting method returning the Title property value.
        /// </summary>
        /// <returns>The Title property value.</returns>
        public static string TitleFormat() {
            return Title;
        }
        
        /// <summary>
        /// The stub formatting method returning the Upload property value.
        /// </summary>
        /// <returns>The Upload property value.</returns>
        public static string UploadFormat() {
            return Upload;
        }
        
        /// <summary>
        /// The stub formatting method returning the Uploaded property value.
        /// </summary>
        /// <returns>The Uploaded property value.</returns>
        public static string UploadedFormat() {
            return Uploaded;
        }
    }
}
