BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.BlogPost
	DROP CONSTRAINT FK_BlogPost_Language
GO
ALTER TABLE dbo.BlogPost
	DROP CONSTRAINT FK_BlogPost_aspnet_Applications
GO

ALTER TABLE dbo.BlogPost
	DROP CONSTRAINT DF_BlogPost_IsPublished
GO

ALTER TABLE dbo.BlogPost
	DROP COLUMN ApplicationId, LanguageId, IsPublished
GO
COMMIT 